#pragma once
#include <cstdint>
#include <utility>
#include <vector>

// =============================================================================
//  SoABase<Derived, IdType, Capacity, GenerationBits>
//
//  CRTP base that provides all bookkeeping and methods for a fixed-capacity
//  SoA. The concrete struct (generated by DEFINE_SOA) only needs to:
//    1. Declare named data arrays as plain members.
//    2. Implement swap_elements(a, b) using those members.
//
//  The user never sees this file. They interact only with the struct produced
//  by DEFINE_SOA and access fields directly:
//
//    bc.position[i]        — in solver loops  (i = packed data index)
//    bc.position[bc.index_of(id)]  — single-body access by stable ID
// =============================================================================

/**
 * @brief CRTP base for fixed-capacity Structure-of-Arrays containers.
 *
 * Provides stable versioned IDs, O(1) add/remove/lookup, and iteration helpers.
 * Concrete structs are generated via DEFINE_SOA; this base is not used
 * directly.
 *
 * @tparam Derived        The generated concrete struct (CRTP pattern).
 * @tparam IdType         Unsigned integer type for IDs (e.g. uint32_t).
 * @tparam Capacity       Compile-time maximum number of live items.
 * @tparam GenerationBits Bits of IdType reserved for the generation counter.
 *                        Set to 0 to disable versioning entirely.
 */
template <typename Derived, typename IdType, IdType Capacity,
          uint8_t GenerationBits>
struct SoABase
{
  // ── Compile-time helpers ─────────────────────────────────────────────────

  static constexpr uint8_t SLOT_BITS = sizeof(IdType) * 8 - GenerationBits;

  static constexpr IdType SLOT_MASK =
      (GenerationBits == 0) ? ~IdType(0)
                            : ((IdType(1) << SLOT_BITS) - IdType(1));

  static constexpr IdType INVALID = ~IdType(0);

  static_assert(Capacity <= SLOT_MASK + IdType(1),
                "SoABase: Capacity exceeds the addressable slot range for the "
                "given GenerationBits.");

  // ── Bookkeeping ───────────────────────────────────────────────────────────

  IdType _size = 0;
  IdType _next_slot = 0;
  IdType _n_free = 0;

  IdType _data_index[Capacity]; ///< slot  → packed data index (or INVALID)
  IdType _ids[Capacity];        ///< packed data index → full versioned ID
  IdType _free_slots[Capacity]; ///< recycled slot stack
  IdType _generation[Capacity]; ///< slot → generation counter

  SoABase()
  {
    for (IdType i = 0; i < Capacity; ++i)
      _generation[i] = 0;
  }

  // ── CRTP accessor ─────────────────────────────────────────────────────────

  Derived &self() { return *static_cast<Derived *>(this); }
  const Derived &self() const { return *static_cast<const Derived *>(this); }

  // ── add ───────────────────────────────────────────────────────────────────

  /**
   * @brief Allocate a new item and return its stable ID.
   *
   * All fields at the new packed slot are zero-initialised (the concrete
   * struct's arrays are value-initialised at construction; add() only
   * advances the bookkeeping, so callers should write fields immediately).
   *
   * @return Stable versioned ID. Store it to reference this item later.
   */
  IdType add()
  {
    IdType slot = (_n_free > 0) ? _free_slots[--_n_free] : _next_slot++;
    IdType data_idx = _size;
    IdType gen = _generation[slot];
    IdType id = make_id(slot, gen);

    _data_index[slot] = data_idx;
    _ids[data_idx] = id;

    ++_size;
    return id;
  }

  // ── emplace ───────────────────────────────────────────────────────────────

  /**
   * @brief Allocate a new item and immediately write fields via a callback.
   *
   * @tparam Fn  Callable with signature `void(IdType id, Derived& self)`.
   * @param  fn  Called right after allocation with the new ID and the
   * collection.
   * @return     Stable versioned ID.
   *
   * @par Example
   * @code
   *   bc.emplace([&](uint32_t id, auto& c) {
   *       uint32_t i    = c.index_of(id);
   *       c.position[i] = {0, 5, 0};
   *       c.mass[i]     = 2.0f;
   *   });
   * @endcode
   */
  template <typename Fn>
  IdType emplace(Fn &&fn)
  {
    IdType id = add();
    fn(id, self());
    return id;
  }

  // ── add_n ─────────────────────────────────────────────────────────────────

  /**
   * @brief Bulk-allocate @p n items, calling @p on_added for each.
   *
   * @tparam Fn       Callable with signature `void(IdType id)`.
   * @param  n        Number of items to allocate.
   * @param  on_added Called once per new item.
   */
  template <typename Fn>
  void add_n(IdType n, Fn &&on_added)
  {
    for (IdType i = 0; i < n; ++i)
      on_added(add());
  }

  // ── remove ────────────────────────────────────────────────────────────────

  /**
   * @brief Remove an item in O(1) via swap-and-pop.
   *
   * The last live item slides into the freed slot; data order is NOT preserved.
   * Stale or already-removed IDs are silently ignored.
   *
   * @param id  Stable ID returned by add() or emplace().
   */
  void remove(IdType id)
  {
    if (!_size)
      return;

    const IdType slot = slot_of(id);
    if (slot >= _next_slot)
      return;

    const IdType idx = _data_index[slot];
    if (idx >= _size)
      return;

    if constexpr (GenerationBits > 0)
      if (gen_of(_ids[idx]) != gen_of(id))
        return;

    const IdType last_idx = _size - 1;
    const IdType last_id = _ids[last_idx];
    const IdType last_slot = slot_of(last_id);

    self().swap_elements(idx, last_idx); // CRTP call into concrete struct
    _ids[idx] = _ids[last_idx];

    _data_index[last_slot] = idx;
    _data_index[slot] = INVALID;

    if constexpr (GenerationBits > 0)
      ++_generation[slot];

    _free_slots[_n_free++] = slot;
    --_size;
  }

  // ── index_of ─────────────────────────────────────────────────────────────

  /**
   * @brief Return the packed data index for a stable ID.
   *
   * Use this when you need to write or read a single item by ID outside
   * of a full iteration loop.
   *
   * No bounds-checking is performed. Call contains() first if the ID may be
   * stale.
   *
   * @param id  Stable ID.
   * @return    Packed array index in [0, count()).
   *
   * @par Example
   * @code
   *   uint32_t i    = bc.index_of(ball);
   *   bc.position[i] = {1, 2, 3};
   * @endcode
   */
  IdType index_of(IdType id) const { return _data_index[slot_of(id)]; }

  // ── contains ──────────────────────────────────────────────────────────────

  /**
   * @brief Return true if @p id refers to a currently live item.
   *
   * @param id  ID to test (may be stale or out-of-range).
   */
  bool contains(IdType id) const
  {
    const IdType slot = slot_of(id);
    if (slot >= _next_slot)
      return false;
    const IdType idx = _data_index[slot];
    if (idx >= _size)
      return false;
    if constexpr (GenerationBits > 0)
      return gen_of(_ids[idx]) == gen_of(id);
    return true;
  }

  // ── Iteration ─────────────────────────────────────────────────────────────

  /**
   * @brief Iterate over all live items by packed data index.
   *
   * @tparam Fn  Callable with signature `void(IdType data_index)`.
   */
  template <typename Fn>
  void for_each_index(Fn &&fn)
  {
    for (IdType i = 0; i < _size; ++i)
      fn(i);
  }

  /// @copydoc for_each_index
  template <typename Fn>
  void for_each_index(Fn &&fn) const
  {
    for (IdType i = 0; i < _size; ++i)
      fn(i);
  }

  /**
   * @brief Iterate over all live items by stable versioned ID.
   *
   * @tparam Fn  Callable with signature `void(IdType id)`.
   */
  template <typename Fn>
  void for_each_id(Fn &&fn)
  {
    for (IdType i = 0; i < _size; ++i)
      fn(_ids[i]);
  }

  /// @copydoc for_each_id
  template <typename Fn>
  void for_each_id(Fn &&fn) const
  {
    for (IdType i = 0; i < _size; ++i)
      fn(_ids[i]);
  }

  // ── Misc ──────────────────────────────────────────────────────────────────

  /// @brief Return the number of currently live items.
  IdType count() const { return _size; }

  /// @brief Return the compile-time maximum capacity.
  static constexpr IdType max_capacity() { return Capacity; }

  /**
   * @brief Remove all items. Generation counters are preserved so old IDs stay
   * stale.
   */
  void clear()
  {
    _size = 0;
    _n_free = 0;
    _next_slot = 0;
  }

  // ── ID helpers ────────────────────────────────────────────────────────────

  static constexpr IdType slot_of(IdType id) { return id & SLOT_MASK; }
  static constexpr IdType gen_of(IdType id) { return id >> SLOT_BITS; }
  static constexpr IdType make_id(IdType slot, IdType g)
  {
    return slot | (g << SLOT_BITS);
  }
};

// =============================================================================
//  DEFINE_SOA(Name, IdType, Capacity, GenBits, FIELDS_MACRO)
// =============================================================================

/**
 * @brief Define a named SoA struct with direct field access.
 *
 * Generates a struct where every field from FIELDS_MACRO becomes a plain
 * array member, giving clean `bc.position[i]` access in loops.
 *
 * @param Name         Name of the generated struct (e.g. BodyCollection).
 * @param IdType       Integer type for IDs (e.g. uint32_t).
 * @param Cap          Compile-time max item count.
 * @param GenBits      Bits reserved for the generation counter (0 = disabled).
 * @param FIELDS_MACRO X-macro listing fields as X(Type, name).
 *
 * @par Minimal example
 * @code
 *   #define PARTICLE_FIELDS(X) \
 *       X(vec3,   position)    \
 *       X(vec3,   velocity)    \
 *       X(float,  mass)
 *
 *   DEFINE_SOA(ParticleCollection, uint32_t, 1024, 8, PARTICLE_FIELDS)
 *
 *   ParticleCollection pc;
 *   uint32_t id = pc.add();
 *   uint32_t i  = pc.index_of(id);
 *   pc.position[i] = {0, 5, 0};
 *   pc.mass[i]     = 1.0f;
 *
 *   // Solver loop — same as the old struct-of-vectors style
 *   for (uint32_t i = 0; i < pc.count(); ++i)
 *       pc.position[i] += pc.velocity[i] * dt;
 *
 *   pc.remove(id);
 *   pc.contains(id); // false
 * @endcode
 */
#define DEFINE_SOA(Name, IdType, Cap, GenBits, FIELDS_MACRO)                 \
  struct Name : SoABase<Name, IdType, Cap, GenBits>                          \
  {                                                                          \
    /* Make Cap available as a plain name inside the struct body so that     \
       DEFINE_SOA_ARRAY_ can use it as an array bound. Template parameters   \
       of the base class are NOT directly in scope in the derived struct. */ \
    static constexpr IdType _cap = Cap;                                      \
                                                                             \
    /* ── Named data arrays ── */                                            \
    FIELDS_MACRO(DEFINE_SOA_ARRAY_)                                          \
                                                                             \
    /* ── swap_elements: called by SoABase::remove() via CRTP ── */          \
    void swap_elements(IdType _a, IdType _b)                                 \
    {                                                                        \
      using std::swap;                                                       \
      FIELDS_MACRO(DEFINE_SOA_SWAP_)                                         \
    }                                                                        \
  };

// Per-field helpers consumed by DEFINE_SOA — not for direct use.
// _cap is the constexpr injected above; it is in scope here because
// DEFINE_SOA_ARRAY_ is always expanded inside the struct body.
#define DEFINE_SOA_ARRAY_(T, name) T name[_cap];
#define DEFINE_SOA_SWAP_(T, name) swap(name[_a], name[_b]);

// =============================================================================
//  DEFINE_DYN_SOA(Name, IdType, GenBits, FIELDS_MACRO)
// =============================================================================

/**
 * @brief CRTP base for dynamically-allocated Structure-of-Arrays containers.
 *
 * Mirrors SoABase exactly, but all bookkeeping arrays are std::vector.
 * Capacity grows at runtime; call reserve() to pre-allocate.
 *
 * @tparam Derived        The generated concrete struct.
 * @tparam IdType         Unsigned integer type for IDs.
 * @tparam GenerationBits Bits reserved for the generation counter.
 */
template <typename Derived, typename IdType, uint8_t GenerationBits>
struct DynSoABase
{
  static constexpr uint8_t SLOT_BITS = sizeof(IdType) * 8 - GenerationBits;
  static constexpr IdType SLOT_MASK =
      (GenerationBits == 0) ? ~IdType(0)
                            : ((IdType(1) << SLOT_BITS) - IdType(1));
  static constexpr IdType INVALID = ~IdType(0);

  IdType _size = 0;
  IdType _next_slot = 0;
  IdType _n_free = 0;

  std::vector<IdType> _data_index;
  std::vector<IdType> _ids;
  std::vector<IdType> _free_slots;
  std::vector<IdType> _generation;

  explicit DynSoABase(IdType initial_capacity = 0)
  {
    if (initial_capacity > 0)
      _reserve_bookkeeping(initial_capacity);
  }

  Derived &self() { return *static_cast<Derived *>(this); }
  const Derived &self() const { return *static_cast<const Derived *>(this); }

  /**
   * @brief Pre-allocate space for @p n items in all arrays.
   *
   * Call before a burst of add() calls to avoid repeated reallocation.
   * After reserving, pointers returned by data arrays are stable until
   * capacity is exceeded again.
   */
  void reserve(IdType n)
  {
    _reserve_bookkeeping(n);
    self().reserve_data(n); // CRTP: each concrete struct reserves its vectors
  }

  /**
   * @brief Allocate a new item and return its stable ID.
   */
  IdType add()
  {
    IdType slot;
    if (_n_free > 0)
    {
      slot = _free_slots[--_n_free];
      _free_slots.pop_back();
    }
    else
    {
      slot = _next_slot++;
      _data_index.push_back(INVALID);
      _generation.push_back(0);
    }

    IdType data_idx = _size;
    IdType gen = _generation[slot];
    IdType id = make_id(slot, gen);

    _data_index[slot] = data_idx;
    _ids.push_back(id);

    self()
        .push_back_data(); // CRTP: push one zero-init element per field vector
    ++_size;
    return id;
  }

  template <typename Fn>
  IdType emplace(Fn &&fn)
  {
    IdType id = add();
    fn(id, self());
    return id;
  }

  template <typename Fn>
  void add_n(IdType n, Fn &&on_added)
  {
    reserve(_size + n);
    for (IdType i = 0; i < n; ++i)
      on_added(add());
  }

  void remove(IdType id)
  {
    if (!_size)
      return;
    const IdType slot = slot_of(id);
    if (slot >= _next_slot)
      return;
    const IdType idx = _data_index[slot];
    if (idx >= _size)
      return;
    if constexpr (GenerationBits > 0)
      if (gen_of(_ids[idx]) != gen_of(id))
        return;

    const IdType last_idx = _size - 1;
    const IdType last_slot = slot_of(_ids[last_idx]);

    self().swap_elements(idx, last_idx);
    _ids[idx] = _ids[last_idx];

    _data_index[last_slot] = idx;
    _data_index[slot] = INVALID;
    if constexpr (GenerationBits > 0)
      ++_generation[slot];

    self().pop_back_data(); // CRTP: pop_back every field vector
    _ids.pop_back();
    _free_slots.push_back(slot);
    ++_n_free;
    --_size;
  }

  IdType index_of(IdType id) const { return _data_index[slot_of(id)]; }

  bool contains(IdType id) const
  {
    const IdType slot = slot_of(id);
    if (slot >= _next_slot)
      return false;
    const IdType idx = _data_index[slot];
    if (idx >= _size)
      return false;
    if constexpr (GenerationBits > 0)
      return gen_of(_ids[idx]) == gen_of(id);
    return true;
  }

  template <typename Fn>
  void for_each_index(Fn &&fn)
  {
    for (IdType i = 0; i < _size; ++i)
      fn(i);
  }
  template <typename Fn>
  void for_each_index(Fn &&fn) const
  {
    for (IdType i = 0; i < _size; ++i)
      fn(i);
  }
  template <typename Fn>
  void for_each_id(Fn &&fn)
  {
    for (IdType i = 0; i < _size; ++i)
      fn(_ids[i]);
  }
  template <typename Fn>
  void for_each_id(Fn &&fn) const
  {
    for (IdType i = 0; i < _size; ++i)
      fn(_ids[i]);
  }

  IdType count() const { return _size; }

  void clear()
  {
    self().clear_data();
    _ids.clear();
    _size = 0;
    _n_free = 0;
    _next_slot = 0;
  }

  static constexpr IdType slot_of(IdType id) { return id & SLOT_MASK; }
  static constexpr IdType gen_of(IdType id) { return id >> SLOT_BITS; }
  static constexpr IdType make_id(IdType s, IdType g)
  {
    return s | (g << SLOT_BITS);
  }

private:
  void _reserve_bookkeeping(IdType n)
  {
    _data_index.reserve(n);
    _ids.reserve(n);
    _free_slots.reserve(n);
    _generation.reserve(n);
  }
};

/**
 * @brief Define a named dynamic SoA struct with direct field access.
 *
 * Same API as DEFINE_SOA, but capacity grows at runtime.
 * Fields become std::vector members; access is still `bc.position[i]`.
 *
 * @warning Pointers into field vectors are invalidated on reallocation.
 *          Call bc.reserve(n) before a burst of bc.add() calls if you need
 *          stable pointers (e.g. before constructing a view for a solver loop).
 *
 * @par Example
 * @code
 *   DEFINE_DYN_SOA(ParticleCollection, uint32_t, 8, PARTICLE_FIELDS)
 *
 *   ParticleCollection pc;
 *   uint32_t id = pc.add();
 *   pc.position[pc.index_of(id)] = {0, 5, 0};
 *
 *   for (uint32_t i = 0; i < pc.count(); ++i)
 *       pc.position[i] += pc.velocity[i] * dt;
 * @endcode
 */
#define DEFINE_DYN_SOA(Name, IdType, GenBits, FIELDS_MACRO)               \
  struct Name : DynSoABase<Name, IdType, GenBits>                         \
  {                                                                       \
    /* ── Named field vectors ── */                                       \
    FIELDS_MACRO(DEFINE_DYN_SOA_VEC_)                                     \
                                                                          \
    explicit Name(IdType initial_capacity = 0)                            \
        : DynSoABase<Name, IdType, GenBits>(initial_capacity) {}          \
                                                                          \
    /* Called by DynSoABase::reserve() */                                 \
    void reserve_data(IdType n) { FIELDS_MACRO(DEFINE_DYN_SOA_RESERVE_) } \
    /* Called by DynSoABase::add() */                                     \
    void push_back_data() { FIELDS_MACRO(DEFINE_DYN_SOA_PUSH_) }          \
    /* Called by DynSoABase::remove() */                                  \
    void pop_back_data() { FIELDS_MACRO(DEFINE_DYN_SOA_POP_) }            \
    /* Called by DynSoABase::clear() */                                   \
    void clear_data() { FIELDS_MACRO(DEFINE_DYN_SOA_CLEAR_) }             \
    /* Called by DynSoABase::remove() */                                  \
    void swap_elements(IdType _a, IdType _b)                              \
    {                                                                     \
      using std::swap;                                                    \
      FIELDS_MACRO(DEFINE_SOA_SWAP_)                                      \
    }                                                                     \
  };

// Per-field helpers for DEFINE_DYN_SOA — not for direct use.
#define DEFINE_DYN_SOA_VEC_(T, name) std::vector<T> name;
#define DEFINE_DYN_SOA_RESERVE_(T, name) name.reserve(n);
#define DEFINE_DYN_SOA_PUSH_(T, name) name.push_back({});
#define DEFINE_DYN_SOA_POP_(T, name) name.pop_back();
#define DEFINE_DYN_SOA_CLEAR_(T, name) name.clear();
// swap reuses DEFINE_SOA_SWAP_ — works for both vector and array indexing.
