RBPS: /home/runner/work/rbps/rbps/include/rbc/gjk/ContactManifoldGenerator.hpp File Reference
ContactManifoldGenerator.hpp File Reference
rbc — Rigid-Body Collision
Build a 1–4 point contact manifold from a single EPA result.
#include "rbc/Contact.hpp"
#include "rbc/gjk/GJK.hpp"
#include "rbc/gjk/EPA.hpp"
#include "rbc/gjk/MinkowskiDiff.hpp"
#include "rbc/shapes/ShapeTypes.hpp"
#include <algorithm>
#include <vector>
Classes
struct rbc::ManifoldDebugCapture
Optional intermediate capture for the visual debugger.
Functions
int rbc::manifold_detail::clip_polygon_by_plane (const m3d::vec3 *poly, int n, const m3d::vec3 &plane_n, const m3d::vec3 &plane_p, m3d::vec3 *out)
Sutherland–Hodgman: clip polygon poly by half-space plane.
int rbc::manifold_detail::reduce_to_4 (const m3d::vec3 *pts, const m3d::scalar *depths, int n, m3d::vec3 *out_pts, m3d::scalar *out_depths)
Reduce n contact candidates to at most 4 by maximising support area.
void rbc::generate_manifold (const m3d::vec3 &epa_normal, m3d::scalar epa_depth, const m3d::vec3 &epa_contact, const Shape &shape_a, const m3d::tf &tf_a, const Shape &shape_b, const m3d::tf &tf_b, ContactManifold &manifold, ManifoldDebugCapture *capture=nullptr)
Build a manifold from an EPA result.
bool rbc::gjk_epa_manifold (const Shape &sa, const m3d::tf &tf_a, const Shape &sb, const m3d::tf &tf_b, ContactManifold &manifold)
Run GJK → EPA → generate_manifold in one call.
Detailed Description
Build a 1–4 point contact manifold from a single EPA result.
manifold_detail::clip_polygon_by_plane and manifold_detail::reduce_to_4 remain inline here because the visual debugger (src/collision_debugger/PipelineRun.hpp) calls them directly from a TU that doesn't link the manifold .cpp.
generate_manifold and gjk_epa_manifold are declared here and defined in ContactManifoldGenerator.cpp using a literal port of the reference clipping algorithm (face/edge feature selection via ConvexHull adjacency tables, neighbor-face boundary planes).
Definition in file ContactManifoldGenerator.hpp.
Function Documentation
clip_polygon_by_plane()
int rbc::manifold_detail::clip_polygon_by_plane (const m3d::vec3 * poly, int n, const m3d::vec3 & plane_n, const m3d::vec3 & plane_p, m3d::vec3 * out) inline
Sutherland–Hodgman: clip polygon poly by half-space plane.
Keeps the part of poly on the positive side of the plane (where dot(point - plane_p, plane_n) >= 0). Output buffer must hold at least 2 * n entries.
Definition at line 56 of file ContactManifoldGenerator.hpp.
References m3d::dot().
reduce_to_4()
int rbc::manifold_detail::reduce_to_4 (const m3d::vec3 * pts, const m3d::scalar * depths, int n, m3d::vec3 * out_pts, m3d::scalar * out_depths) inline
Reduce n contact candidates to at most 4 by maximising support area.
Greedy: deepest, then farthest from it, then farthest from that segment, then farthest from the resulting triangle.
Definition at line 88 of file ContactManifoldGenerator.hpp.
References m3d::abs(), m3d::cross(), m3d::dot(), and m3d::length_sq().
generate_manifold()
void rbc::generate_manifold (const m3d::vec3 & epa_normal, m3d::scalar epa_depth, const m3d::vec3 & epa_contact, const Shape & shape_a, const m3d::tf & tf_a, const Shape & shape_b, const m3d::tf & tf_b, ContactManifold & manifold, ManifoldDebugCapture * capture = nullptr)
Build a manifold from an EPA result.
Pass a non-null capture to receive per-stage intermediates (used by the visual debugger). Defined in ContactManifoldGenerator.cpp.
References rbc::generate_manifold().
Referenced by rbc::generate_manifold().
gjk_epa_manifold()
bool rbc::gjk_epa_manifold (const Shape & sa, const m3d::tf & tf_a, const Shape & sb, const m3d::tf & tf_b, ContactManifold & manifold)
Run GJK → EPA → generate_manifold in one call.
Returns false if GJK reports separation or EPA fails to converge.
References rbc::gjk_epa_manifold().
Referenced by rbc::gjk_epa_manifold(), and rbc::CollisionAlgorithm< A, B >::test().