RBPS: visr — Visualizer
visr — Visualizer
Optional raylib + ImGui visualizer for the RBPS engine.
Files
file Command.hpp
Command types the visualizer can send back to the physics engine.
file CommandDispatch.hpp
Single entry point that applies any Command to a World.
file DebugChannel.hpp
Per-channel state — frame counter, pause control, tracked-series storage.
file InProcessTransport.hpp
Same-process, two-thread transport between physics and render.
file Snapshot.hpp
Plain data types that flow from the physics engine to the visualizer.
file SnapshotBuilder.hpp
Convert a rbps::World into a FrameSnapshot POD copy.
file CameraSystem.hpp
Free-look fly-camera (WASD + Q/E + RMB drag) for the visualizer.
file RenderSystem.hpp
Per-frame raylib + ImGui + ImPlot pass.
file SelectionSystem.hpp
Left-click ray-pick selection driven entirely from the snapshot.
file Transport.hpp
Transport contract (push_snapshot + poll_command) and detection trait.
file Panels.hpp
ImGui + ImPlot panels (sim controls, body inspector, contact graphs, …).
file RaylibDraw.hpp
Stateless draw helpers — convert every *Snap to raylib draw calls.
file VisrApp.hpp
Top-level visualizer app: owns the World, thread, and render systems.
Classes
struct visr::CmdSetTimestep
Change the simulation timestep and/or substep count live.
struct visr::CmdSelectBody
Select a body by stable ID.
struct visr::CmdSelectCollider
Select a collider by stable ID.
struct visr::CmdClearSelection
Clear all selection state.
struct visr::CmdApplyImpulse
Apply an instantaneous linear impulse at a world-space point.
struct visr::CmdTeleportBody
Teleport a body (position + orientation) and zero its velocities.
struct visr::CmdZeroVelocity
Zero a body's linear and angular velocities.
struct visr::CmdSetJointTarget
Set the position target for an actuated joint.
struct visr::CmdSetJointSpeed
Set the speed target for an actuated joint.
struct visr::CmdSetJointDamping
Update a joint's damping coefficient live.
struct visr::CmdTrackQuantity
Subscribe / unsubscribe a tracked quantity for the live plots.
struct visr::CmdSetGravity
Set the global gravity vector.
struct visr::CmdPause
Pause the simulation — physics thread stops calling world.step().
struct visr::CmdResume
Resume a previously paused simulation.
struct visr::TrackedSeries
Ring buffer of (frame, sim_time, value) samples for one tracked quantity.
struct visr::DebugChannel< Transport >
Owns transport + per-channel state (frame counter, pause, tracked series).
struct visr::InProcessTransport
Lock-free snapshot publish + mutex-guarded command queue.
struct visr::SpherSnap
POD: sphere shape parameters.
struct visr::BoxSnap
POD: oriented-box shape parameters.
struct visr::CapsuleSnap
POD: capsule shape parameters.
struct visr::PlaneSnap
POD: infinite plane (normal · x = distance).
struct visr::ConeSnap
POD: cone shape parameters.
struct visr::CylinderSnap
POD: cylinder shape parameters.
struct visr::EllipsoidSnap
POD: ellipsoid shape parameters.
struct visr::HeightmapSnap
POD: heightmap dimensions (height data is NOT snapshotted).
struct visr::MeshSnap
POD: triangle mesh dimensions (vertex/face data is NOT snapshotted).
struct visr::ConvexHullSnap
POD: convex polytope — vertex + face data deep-copied per frame.
struct visr::BodySnap
Per-body snapshot (POD copy of BodyCollection row data).
struct visr::ColliderSnap
Per-collider snapshot.
struct visr::ContactSnap
Per-contact snapshot, captured after the last substep.
struct visr::JointSnap
Per-joint snapshot (POD copy of JointCollection row data).
struct visr::ConstraintSnap
Per-constraint snapshot (one entry per XPBD constraint row).
struct visr::FrameSnapshot
Top-level frame — everything the visualizer needs for one tick.
struct visr::detail::ShapeToSnap
Visitor that maps each rbc::Shape alternative to its *Snap POD.
struct visr::CameraSystem
Free-look camera with adjustable move speed and look sensitivity.
struct visr::RenderSystem
Owns the per-frame render pass and the post-frame plot-export hook.
struct visr::AABB3
Plain float AABB used by the ray-pick fast path.
struct visr::SelectionSystem
Mouse-pick selection over the latest snapshot.
struct visr::is_debug_transport< T >
Compile-time predicate: does T satisfy the DebugTransport contract?
struct visr::NullTransport
Zero-overhead transport that drops everything.
struct visr::ui::PlotExportRequest
Plot-export rendezvous between the panel and RenderSystem.
struct visr::ui::SelectionState
Currently-selected body / collider / joint / contact, sentinel = UINT32_MAX.
struct visr::draw::DrawFlags
Toggles for which overlays draw_scene renders.
Macros
#define ASSERT_DEBUG_TRANSPORT(T)
Static-assert that T is a valid transport.
Typedefs
using visr::Command = std::variant< CmdPause, CmdResume, CmdSetTimestep, CmdSelectBody, CmdSelectCollider, CmdClearSelection, CmdApplyImpulse, CmdTeleportBody, CmdZeroVelocity, CmdSetJointTarget, CmdSetJointSpeed, CmdSetJointDamping, CmdTrackQuantity, CmdSetGravity, CmdSpawnBody >
Variant over every command type.
using visr::ShapeSnap = std::variant< SpherSnap, BoxSnap, CapsuleSnap, PlaneSnap, CylinderSnap, ConeSnap, EllipsoidSnap, HeightmapSnap, MeshSnap, ConvexHullSnap >
Variant over all *Snap shape PODs.
Enumerations
enum class visr::TrackTarget : uint8_t
Quantities the visualizer can plot live.
enum class visr::JointTypeSnap : uint8_t
Joint kind enum mirrored from rbps::JointType.
enum class visr::ConstraintTypeSnap : uint8_t
Constraint kind enum mirrored from rbps::ConstraintType.
Functions
void visr::dispatch_command (rbps::World &world, const Command &cmd)
Apply cmd to world (visit-based dispatch).
FrameSnapshot visr::build_snapshot (const rbps::World &world, uint64_t frame_index, double sim_time)
Build a FrameSnapshot from the current state of world.
template<typename T >
void visr::ui::draw_all (DebugChannel< T > &channel, InProcessTransport &transport, const FrameSnapshot &snap, SelectionState &sel)
Draw every panel for one frame.
void visr::draw::draw_scene (const FrameSnapshot &snap, const DrawFlags &flags={}, uint32_t sel_body=UINT32_MAX, uint32_t sel_contact=UINT32_MAX, uint32_t sel_joint=UINT32_MAX)
Render the full scene from a snapshot in one call.
Detailed Description
Optional raylib + ImGui visualizer for the RBPS engine.
Built only when CMake is configured with -DRBPS_BUILD_VISR=ON. The visualizer runs a producer/consumer split:
Physics thread owns the World, runs step(), and publishes a FrameSnapshot (POD copy of the simulation state) to the transport.
Render thread consumes the latest snapshot, runs the camera / selection / render systems, and pushes user-input Commands back through the transport for the physics thread to apply.
The transport is templated so the visualizer can be wired to a network link or shared-memory channel just as easily as the default InProcessTransport. VisrApp ties everything together — most users just instantiate it, call run(), and never touch the lower layers.
Macro Definition Documentation
ASSERT_DEBUG_TRANSPORT
#define ASSERT_DEBUG_TRANSPORT (T)
Value:
        static_assert(::visr::is_debug_transport<T>::value, \
                      #T " must implement push_snapshot() and poll_command()")
Static-assert that T is a valid transport.
Drop at the top of any function template that takes a transport so the contract violation reports at the call site instead of deep inside the implementation.
Definition at line 66 of file Transport.hpp.
Typedef Documentation
Command
using visr::Command = typedef std::variant< CmdPause, CmdResume, CmdSetTimestep, CmdSelectBody, CmdSelectCollider, CmdClearSelection, CmdApplyImpulse, CmdTeleportBody, CmdZeroVelocity, CmdSetJointTarget, CmdSetJointSpeed, CmdSetJointDamping, CmdTrackQuantity, CmdSetGravity, CmdSpawnBody>
Variant over every command type.
Dispatched in CommandDispatch.hpp via std::visit. Add a new command by extending this variant and adding an else if constexpr arm there.
Definition at line 154 of file Command.hpp.
ShapeSnap
using visr::ShapeSnap = typedef std::variant< SpherSnap, BoxSnap, CapsuleSnap, PlaneSnap, CylinderSnap, ConeSnap, EllipsoidSnap, HeightmapSnap, MeshSnap, ConvexHullSnap >
Variant over all *Snap shape PODs.
Mirror of rbc::Shape for the visualizer. To add a new shape: extend this variant and add an arm in SnapshotBuilder.hpp's ShapeToSnap.
Definition at line 70 of file Snapshot.hpp.
Enumeration Type Documentation
TrackTarget
enum class visr::TrackTarget : uint8_t strong
Quantities the visualizer can plot live.
The render thread sends CmdTrackQuantity to subscribe / unsubscribe; the physics thread samples these values into a TrackedSeries ring buffer in DebugChannel.
Definition at line 107 of file Command.hpp.
Function Documentation
dispatch_command()
void visr::dispatch_command (rbps::World & world, const Command & cmd) inline
Apply cmd to world (visit-based dispatch).
Channel-level commands (CmdPause, CmdResume, CmdTrackQuantity) are intentional no-ops here — they're handled in DebugChannel::poll so the world isn't touched when the user just pauses or starts plotting a value.
Definition at line 30 of file CommandDispatch.hpp.
References rbps::apply_positional_velocity_constraint_impulse(), rbps::World::bodies, rbps::ColliderParams::body_id, rbps::World::create_body(), rbps::World::create_collider(), rbps::World::joints, rbps::World::substeps, and rbps::World::timestep.
Referenced by visr::DebugChannel< Transport >::poll().
build_snapshot()
FrameSnapshot visr::build_snapshot (const rbps::World & world, uint64_t frame_index, double sim_time) inline
Build a FrameSnapshot from the current state of world.
Iterates every body / collider / contact / joint / constraint row and copies the data into POD *Snap structs. Stable IDs (not packed slot indices) are written, so the visualizer can keep its selection state consistent across frames where a body has been swap-popped.
Parameters
world The physics world to snapshot.
frame_index Caller-managed frame counter (for the FrameSnapshot::frame_index field).
sim_time Caller-managed simulation time in seconds.
Definition at line 118 of file SnapshotBuilder.hpp.
References rbps::World::bodies, rbps::World::broad_phase_state, rbps::World::colliders, rbps::World::constraints, rbps::World::contacts, rbps::World::joints, rbc::BroadPhaseState::pairs, m3d::tf::pos, m3d::tf::rot, m3d::rotate(), rbps::World::substeps, rbps::World::timestep, and visr::detail::to_shape_snap().
Referenced by visr::DebugChannel< Transport >::push().
draw_all()
template<typename T > void visr::ui::draw_all (DebugChannel< T > & channel, InProcessTransport & transport, const FrameSnapshot & snap, SelectionState & sel) inline
Draw every panel for one frame.
Called once per frame from RenderSystem::update between rlImGuiBegin and rlImGuiEnd. Internally dispatches to the sim-control / body / collider / contact / joint / graph panels.
Definition at line 989 of file Panels.hpp.
draw_scene()
void visr::draw::draw_scene (const FrameSnapshot & snap, const DrawFlags & flags = {}, uint32_t sel_body = UINT32_MAX, uint32_t sel_contact = UINT32_MAX, uint32_t sel_joint = UINT32_MAX) inline
Render the full scene from a snapshot in one call.
Iterates colliders, contacts, joints, and (when selected) the highlighted body's axes. Highlight IDs default to UINT32_MAX — pass an actual stable ID to draw the body in GREEN.
Definition at line 549 of file RaylibDraw.hpp.