RBPS: internals — Algorithm implementations
internals — Algorithm implementations
Lower-level building blocks documented for maintainers.
Files
file BoxBox.hpp
Analytic Box–Box collision algorithm (SAT + face/face manifold).
file CapsuleBox.hpp
Analytic Capsule–Box collision algorithm (SAT).
file CapsuleCapsule.hpp
Analytic Capsule–Capsule collision algorithm.
file HeightmapCollision.hpp
Analytic shape–Heightmap collision algorithms.
file MeshCollision.hpp
Analytic shape–Mesh collision algorithms.
file PlaneCollision.hpp
Analytic convex-shape-vs-Plane collision algorithms.
file SphereBox.hpp
Analytic Sphere–Box collision algorithm.
file SphereCapsule.hpp
Analytic Sphere–Capsule collision algorithm.
file SphereSphere.hpp
Analytic Sphere–Sphere collision algorithm.
file TriangleUtils.hpp
Triangle/segment geometry helpers shared by mesh + heightmap collision.
file MinkowskiDiff.hpp
Implicit Minkowski difference A ⊖ B used by GJK and EPA.
Classes
struct rbc::CollisionAlgorithm< Box, Box >
Box vs Box via 15-axis SAT; produces a face/face manifold (1–4 contacts).
struct rbc::CollisionAlgorithm< Capsule, Box >
Capsule vs Box via SAT on 6 axes; 1 or 2 contacts depending on the feature.
struct rbc::CollisionAlgorithm< Box, Capsule >
Box vs Capsule — reuses <Capsule, Box> and flips the normal.
struct rbc::CollisionAlgorithm< Capsule, Capsule >
Capsule vs Capsule via segment-segment closest-points; 1 or 2 contacts.
struct rbc::CollisionAlgorithm< Sphere, Box >
Closest-point analytic test for sphere vs OBB; produces 1 contact point.
struct rbc::CollisionAlgorithm< Box, Sphere >
Box vs Sphere — reuses <Sphere, Box> and flips the normal.
struct rbc::CollisionAlgorithm< Sphere, Capsule >
Sphere vs Capsule via segment-distance reduction; 1 contact point.
struct rbc::CollisionAlgorithm< Capsule, Sphere >
Capsule vs Sphere — reuses <Sphere, Capsule> and flips the normal.
struct rbc::CollisionAlgorithm< Sphere, Sphere >
Distance test: overlap iff |center_b - center_a| < r_a + r_b.
struct rbc::SAPEndpoint
Internal: one sorted endpoint per AABB edge on the projection axis.
struct rbc::BPObject
Internal: per-registered-object record stored in BroadPhaseState::objects.
struct rbc::CollisionAlgorithm< A, B >
Primary template: GJK + EPA + manifold generation for convex pairs.
struct rbc::CollisionAlgorithmSym< A, B >
Symmetric helper: (B, A) reuses (A, B) and flips the contact normal.
struct rbc::MinkowskiDiff
Minkowski difference of two shapes, accessed only through its support function.
struct visr::detail::ShapeToSnap
Visitor that maps each rbc::Shape alternative to its *Snap POD.
struct visr::AABB3
Plain float AABB used by the ray-pick fast path.
Functions
m3d::vec3 rbc::tri::closest_point_on_triangle (const m3d::vec3 &P, const m3d::vec3 &A, const m3d::vec3 &B, const m3d::vec3 &C)
Closest point on triangle ABC to query point P.
m3d::scalar rbc::tri::sq_dist_point_triangle (const m3d::vec3 &P, const m3d::vec3 &A, const m3d::vec3 &B, const m3d::vec3 &C)
Squared distance from point P to triangle ABC.
m3d::vec3 rbc::tri::closest_point_on_segment (const m3d::vec3 &P, const m3d::vec3 &Q, const m3d::vec3 &X)
Closest point on segment [P, Q] to query point X.
m3d::scalar rbc::tri::sq_dist_segment_triangle (const m3d::vec3 &P, const m3d::vec3 &Q, const m3d::vec3 &A, const m3d::vec3 &B, const m3d::vec3 &C)
Squared distance from segment [P, Q] to triangle ABC.
bool rbc::tri::sphere_vs_triangle (const m3d::vec3 &centre, m3d::scalar radius, const m3d::vec3 &A, const m3d::vec3 &B, const m3d::vec3 &C, const m3d::vec3 &face_normal, ContactManifold &manifold)
Test a sphere against a single triangle.
bool rbc::tri::capsule_vs_triangle (const m3d::vec3 &cap_p1, const m3d::vec3 &cap_p2, m3d::scalar radius, const m3d::vec3 &A, const m3d::vec3 &B, const m3d::vec3 &C, const m3d::vec3 &face_normal, ContactManifold &manifold)
Test a capsule against a single triangle.
void rbc::bp_insertion_sort (std::vector< SAPEndpoint > &endpoints)
Insertion sort on the endpoint list — O(n) on nearly-sorted input.
void rbc::bp_sweep (BroadPhaseState &bp)
Sweep the sorted endpoint list and fill bp.pairs.
template<std::size_t I, std::size_t J>
bool rbc::detail::dispatch_pair (const Shape &a, const m3d::tf &tf_a, const Shape &b, const m3d::tf &tf_b, ContactManifold &out)
One concrete dispatch function per (A, B) shape pair.
template<std::size_t I, std::size_t... Js>
constexpr auto rbc::detail::make_row (std::index_sequence< Js... >)
Build one row I of the dispatch table.
template<std::size_t... Is>
constexpr auto rbc::detail::make_table (std::index_sequence< Is... >)
Expand rows over the row-index pack to produce the full N×N table.
uint32_t rbps::push_joint (JointCollection &jc, ConstraintBlock cb, u_short c_count, uint32_t body_1, uint32_t body_2, vec3 r_1, vec3 r_2, JointType type, JointActuationType actuation, bool limited, scalar lower, scalar upper, vec3 main_axis, vec3 limit_axis, scalar damping)
Internal helper: write all joint fields for a freshly-allocated row.
void rbps::solve_normal_constraint (ContactList &cl, uint32_t i, BodyCollection &bc, m3d::scalar inv_h, m3d::scalar penetration, m3d::vec3 r_a_wc, m3d::vec3 r_b_wc)
Non-penetration (normal) constraint — solver inner loop.
void rbps::solve_tangent_constraint (ContactList &cl, uint32_t i, BodyCollection &bc, m3d::scalar inv_h)
Tangential (friction) constraint — solver inner loop.
vec3 rbps::compute_angle_limit_correction (scalar &phi, vec3 n, vec3 n_1, vec3 n_2, scalar lower_limit, scalar upper_limit)
Clamps the joint angle within limits and computes the rotational correction vector.
ShapeSnap visr::detail::to_shape_snap (const rbc::Shape &s)
Variant-level helper: dispatch a shape into its ShapeSnap.
Variables
constexpr std::size_t rbc::detail::kShapeCount = std::variant_size_v<decltype(Shape::v)>
Number of distinct shape kinds — single source of truth from the variant.
constexpr auto rbc::detail::DispatchTable
The compile-time N×N dispatch table.
Detailed Description
Lower-level building blocks documented for maintainers.
Symbols here are documented but not part of the public API: collision algorithm specialisations, GJK / EPA, the constraint solver, broad-phase sweep helpers, etc. They live in a separate sidebar group so casual users browsing the API aren't overwhelmed.
Function Documentation
closest_point_on_triangle()
m3d::vec3 rbc::tri::closest_point_on_triangle (const m3d::vec3 & P, const m3d::vec3 & A, const m3d::vec3 & B, const m3d::vec3 & C) inline
Closest point on triangle ABC to query point P.
Barycentric / Voronoi-region method. Reference: Ericson, Real-Time Collision Detection, §5.1.5.
Definition at line 22 of file TriangleUtils.hpp.
References m3d::dot().
Referenced by rbc::tri::capsule_vs_triangle(), rbc::tri::sphere_vs_triangle(), and rbc::tri::sq_dist_point_triangle().
sq_dist_segment_triangle()
m3d::scalar rbc::tri::sq_dist_segment_triangle (const m3d::vec3 & P, const m3d::vec3 & Q, const m3d::vec3 & A, const m3d::vec3 & B, const m3d::vec3 & C) inline
Squared distance from segment [P, Q] to triangle ABC.
Tests every segment endpoint against the triangle plus every triangle edge against the segment, returning the minimum.
Definition at line 100 of file TriangleUtils.hpp.
References m3d::clamp(), m3d::dot(), m3d::EPSILON, m3d::length_sq(), m3d::min(), and rbc::tri::sq_dist_point_triangle().
Referenced by rbc::tri::capsule_vs_triangle().
sphere_vs_triangle()
bool rbc::tri::sphere_vs_triangle (const m3d::vec3 & centre, m3d::scalar radius, const m3d::vec3 & A, const m3d::vec3 & B, const m3d::vec3 & C, const m3d::vec3 & face_normal, ContactManifold & manifold) inline
Test a sphere against a single triangle.
Returns true and fills manifold (1 contact point) if the sphere penetrates the triangle. The contact normal points from the triangle face toward the sphere.
Parameters
face_normal Precomputed unit triangle normal (avoids re-deriving).
Definition at line 174 of file TriangleUtils.hpp.
References m3d::abs(), rbc::tri::closest_point_on_triangle(), m3d::dot(), m3d::EPSILON, m3d::length_sq(), rbc::ContactManifold::normal, rbc::ContactManifold::num_points, rbc::ContactPoint::penetration_depth, rbc::ContactManifold::points, rbc::ContactPoint::position, and m3d::sqrt().
capsule_vs_triangle()
bool rbc::tri::capsule_vs_triangle (const m3d::vec3 & cap_p1, const m3d::vec3 & cap_p2, m3d::scalar radius, const m3d::vec3 & A, const m3d::vec3 & B, const m3d::vec3 & C, const m3d::vec3 & face_normal, ContactManifold & manifold) inline
Test a capsule against a single triangle.
Returns true and fills manifold (1 contact point) if the capsule penetrates the triangle.
Definition at line 213 of file TriangleUtils.hpp.
References rbc::tri::closest_point_on_triangle(), m3d::dot(), m3d::EPSILON, m3d::length_sq(), rbc::ContactManifold::normal, rbc::ContactManifold::num_points, rbc::ContactPoint::penetration_depth, rbc::ContactManifold::points, rbc::ContactPoint::position, rbc::tri::sq_dist_segment_triangle(), and m3d::sqrt().
dispatch_pair()
template<std::size_t I, std::size_t J> bool rbc::detail::dispatch_pair (const Shape & a, const m3d::tf & tf_a, const Shape & b, const m3d::tf & tf_b, ContactManifold & out)
One concrete dispatch function per (A, B) shape pair.
Template indices come from std::variant's alternative list, so the runtime shape.v.index() and the type identity match by construction.
Definition at line 145 of file Dispatcher.hpp.
References rbc::CollisionAlgorithm< A, B >::test().
make_row()
template<std::size_t I, std::size_t... Js> constexpr auto rbc::detail::make_row (std::index_sequence< Js... >) constexpr
Build one row I of the dispatch table.
Instantiates dispatch_pair<I, J> for every J in the column index pack.
Definition at line 169 of file Dispatcher.hpp.
push_joint()
uint32_t rbps::push_joint (JointCollection & jc, ConstraintBlock cb, u_short c_count, uint32_t body_1, uint32_t body_2, vec3 r_1, vec3 r_2, JointType type, JointActuationType actuation, bool limited, scalar lower, scalar upper, vec3 main_axis, vec3 limit_axis, scalar damping) inline
Internal helper: write all joint fields for a freshly-allocated row.
Factored out so the three create_*_joint helpers don't duplicate the 17 field assignments.
Definition at line 137 of file JointAPI.hpp.
solve_normal_constraint()
void rbps::solve_normal_constraint (ContactList & cl, uint32_t i, BodyCollection & bc, m3d::scalar inv_h, m3d::scalar penetration, m3d::vec3 r_a_wc, m3d::vec3 r_b_wc)
Non-penetration (normal) constraint — solver inner loop.
Computes Δλ = (−d − α·λ_old) / (w_a + w_b + α) and applies the resulting positional impulse to both bodies.
solve_tangent_constraint()
void rbps::solve_tangent_constraint (ContactList & cl, uint32_t i, BodyCollection & bc, m3d::scalar inv_h)
Tangential (friction) constraint — solver inner loop.
Computes the tangential slip Δp_t since the last substep and applies a Coulomb-clamped friction impulse.
compute_angle_limit_correction()
vec3 rbps::compute_angle_limit_correction (scalar & phi, vec3 n, vec3 n_1, vec3 n_2, scalar lower_limit, scalar upper_limit)
Clamps the joint angle within limits and computes the rotational correction vector.
If the current angle φ is outside [lower_limit, upper_limit], this function:
Clamps φ into the valid range.
Builds a quaternion representing rotation of φ about axis n.
Rotates the initial limit-axis vector n_1 by that quaternion.
Computes δq = n₁_rotated × n₂, which measures the misalignment.
If φ was already within the limits, returns the zero vector.
Parameters
[in,out] phi Current joint angle (in/out). On exit, clamped to [lower_limit, upper_limit].
[in] n Joint’s main rotation axis (unit vector in world space).
[in] n_1 First body’s limit-axis vector (in world space).
[in] n_2 Second body’s limit-axis vector (in world space).
[in] lower_limit Minimum allowed angle (radians).
[in] upper_limit Maximum allowed angle (radians).
Returns
Correction vector δq to drive the axes into alignment.
Variable Documentation
kShapeCount
constexpr std::size_t rbc::detail::kShapeCount = std::variant_size_v<decltype(Shape::v)> constexpr
Number of distinct shape kinds — single source of truth from the variant.
Add a shape to Shape::v in ShapeTypes.hpp and the table grows automatically.
Definition at line 194 of file Dispatcher.hpp.