RBPS: math3d — 3D math primitives
math3d — 3D math primitives
Foundational vector, matrix, quaternion, and transform types.
Files
file core.hpp
Scalar alias, math constants, and thin wrappers around <cmath>.
file mat3.hpp
3×3 matrices: dense mat3 and symmetric smat3.
file math3d.hpp
Umbrella header that pulls in all math3d types in one include.
file quat.hpp
Unit quaternion type for rigid-body orientation.
file tf.hpp
Rigid transform: a translation paired with a quaternion rotation.
file vec2i.hpp
2-component integer vector — used for grid coordinates and pixel indices.
file vec3.hpp
3-component floating-point vector and inline operators.
Classes
struct m3d::mat3
Dense 3×3 matrix in column-major layout.
struct m3d::smat3
Symmetric 3×3 matrix stored as 6 unique scalars.
struct m3d::tf
Rigid (SE(3)) transform = translation + rotation.
struct m3d::vec2i
2-component vector of int (cartesian x, y).
Typedefs
using m3d::scalar = double
Default floating-point type for the whole engine.
Functions
template<typename T >
T m3d::clamp (T v, T lo, T hi)
Clamp v into [lo, hi].
scalar m3d::to_radians (scalar degrees)
Convert an angle from degrees to radians.
scalar m3d::min (scalar x, scalar y)
std::min for scalar.
scalar m3d::max (scalar x, scalar y)
std::max for scalar.
scalar m3d::abs (scalar x)
std::abs for scalar.
scalar m3d::sqrt (scalar x)
std::sqrt for scalar.
scalar m3d::sin (scalar x)
std::sin for scalar.
scalar m3d::cos (scalar x)
std::cos for scalar.
scalar m3d::atan2 (scalar y, scalar x)
std::atan2 for scalar.
mat3 m3d::mat3_cast (const quat &q)
Convert a unit quaternion to its equivalent rotation mat3.
smat3 m3d::operator* (scalar s, const smat3 &m)
Left-side scalar multiplication for smat3.
mat3 m3d::operator* (const mat3 &lhs, const smat3 &rhs)
Mixed mat3 * smat3 product, returning a dense mat3.
quat m3d::normalize (const quat &q)
Renormalise q so its magnitude is 1.
quat m3d::conjugate (const quat &q)
Quaternion conjugate (w, -x, -y, -z).
vec3 m3d::rotate (const vec3 &v, const quat &q)
Rotate vector v by quaternion q.
vec3 m3d::rotate (const quat &q, const vec3 &v)
Argument-flipped overload; same result as rotate(v, q).
vec3 m3d::to_rpy (const quat &q)
Convert a unit quaternion to roll–pitch–yaw (Tait-Bryan).
vec2i m3d::operator* (int s, const vec2i &v)
Left-side scalar multiplication (s * v).
int m3d::dot (const vec2i &a, const vec2i &b)
Dot (inner) product of two 2D integer vectors.
int m3d::cross (const vec2i &a, const vec2i &b)
2D cross product (signed scalar).
vec3 m3d::operator* (scalar s, const vec3 &v)
Left-side scalar multiplication (s * v).
scalar m3d::dot (const vec3 &a, const vec3 &b)
Dot (inner) product of two vectors.
vec3 m3d::cross (const vec3 &a, const vec3 &b)
Cross product (a × b), right-handed.
scalar m3d::length_sq (const vec3 &v)
Squared length of v.
scalar m3d::length (const vec3 &v)
Euclidean length of v.
scalar m3d::magnitude (const vec3 &v)
Alias of length, more natural in some physics contexts.
vec3 m3d::normalize (const vec3 &v)
Return v / length(v), or the zero vector if v is near zero.
Variables
constexpr scalar m3d::PI = 3.14159265358979323846
Pi.
constexpr scalar m3d::EPSILON = 1e-9
Generic small-number tolerance used by is_approx helpers.
constexpr scalar m3d::ERROR_ULP = 2.107342e-08
Unit-in-the-Last-Place threshold for double.
Detailed Description
Foundational vector, matrix, quaternion, and transform types.
Header-only. All types live in the m3d namespace and use a single floating-point alias (scalar = double) so the engine's precision can be swapped in one place.
Typedef Documentation
scalar
using m3d::scalar = typedef double
Default floating-point type for the whole engine.
Aliased here so a future port to float (or to a fixed-point type for embedded targets) is a single-line change.
Definition at line 36 of file core.hpp.
Function Documentation
clamp()
template<typename T > T m3d::clamp (T v, T lo, T hi) inline
Clamp v into [lo, hi].
Template Parameters
T Any orderable type.
Parameters
v Value to clamp.
lo Lower bound (inclusive).
hi Upper bound (inclusive).
Returns
lo if v < lo, hi if v > hi, otherwise v.
Definition at line 73 of file core.hpp.
Referenced by rbc::tri::closest_point_on_segment(), rbc::tri::sq_dist_segment_triangle(), rbc::CollisionAlgorithm< Capsule, Capsule >::test(), rbc::CollisionAlgorithm< Capsule, Box >::test(), rbc::CollisionAlgorithm< Sphere, Box >::test(), and rbc::CollisionAlgorithm< Sphere, Capsule >::test().
to_radians()
scalar m3d::to_radians (scalar degrees) inline
Convert an angle from degrees to radians.
Parameters
degrees Angle in degrees.
Returns
Angle in radians.
Definition at line 84 of file core.hpp.
References m3d::PI.
mat3_cast()
mat3 m3d::mat3_cast (const quat & q) inline
Convert a unit quaternion to its equivalent rotation mat3.
Parameters
q Unit quaternion. The result is undefined if q is far from unit length.
Returns
The 3×3 rotation matrix that performs the same rotation as q.
Definition at line 166 of file mat3.hpp.
Referenced by rbc::compute_aabb(), rbc::compute_aabb(), rbc::compute_aabb(), and rbc::compute_aabb().
operator*()
mat3 m3d::operator* (const mat3 & lhs, const smat3 & rhs) inline
Mixed mat3 * smat3 product, returning a dense mat3.
Used when transforming the (symmetric) inertia tensor into world space: I_world = R * I_local * R^T. The intermediate result is generally not symmetric, so a dense matrix is returned.
Definition at line 302 of file mat3.hpp.
References m3d::smat3::yz, and m3d::smat3::zz.
normalize() [1/2]
quat m3d::normalize (const quat & q) inline
Renormalise q so its magnitude is 1.
If the magnitude is already within one ULP of 1, applies the cheap Padé approximation q * (2 / (1 + |q|²)) instead of a sqrt. If q is degenerate (near zero) the identity quaternion is returned.
Examples
test_quat.cpp.
Definition at line 153 of file quat.hpp.
References m3d::abs(), m3d::EPSILON, and m3d::sqrt().
Referenced by rbc::convex_hull_data_create(), rbc::get_generic_face_corners(), rbc::mesh_data_create(), rbc::support(), rbc::CollisionAlgorithm< Box, Box >::test(), and m3d::to_rpy().
conjugate()
quat m3d::conjugate (const quat & q) inline
Quaternion conjugate (w, -x, -y, -z).
For unit quaternions, this is also the inverse: q * conjugate(q) ≈ identity.
Examples
test_quat.cpp.
Definition at line 175 of file quat.hpp.
Referenced by m3d::tf::inverse_rotate_vector().
rotate()
vec3 m3d::rotate (const vec3 & v, const quat & q) inline
Rotate vector v by quaternion q.
Computes q * v * q⁻¹ via the optimised cross-product form: v + 2 * cross(q.xyz, cross(q.xyz, v) + q.w * v).
Examples
test_quat.cpp.
Definition at line 188 of file quat.hpp.
References m3d::cross().
Referenced by visr::build_snapshot(), rbps::create_collider(), rbps::DEFINE_DYN_SOA(), m3d::tf::inverse_rotate_vector(), m3d::rotate(), m3d::tf::rotate_vector(), and m3d::tf::transform_point().
to_rpy()
vec3 m3d::to_rpy (const quat & q) inline
Convert a unit quaternion to roll–pitch–yaw (Tait-Bryan).
Pitch is clamped to ±90° at the gimbal-lock singularity to avoid NaN from asin on slightly out-of-range values.
Returns
vec3{roll, pitch, yaw} in radians.
Definition at line 214 of file quat.hpp.
References m3d::abs(), m3d::atan2(), and m3d::normalize().
dot() [1/2]
int m3d::dot (const vec2i & a, const vec2i & b) inline
Dot (inner) product of two 2D integer vectors.
Returns
a.x*b.x + a.y*b.y.
Definition at line 114 of file vec2i.hpp.
Referenced by rbc::tri::capsule_vs_triangle(), rbc::manifold_detail::clip_polygon_by_plane(), rbc::tri::closest_point_on_segment(), rbc::tri::closest_point_on_triangle(), rbc::compute_inertia_tensor(), rbc::compute_volume(), rbc::convex_hull_data_create(), rbc::face_corners(), rbc::face_corners(), rbc::plane_world_d(), rbc::manifold_detail::reduce_to_4(), rbc::tri::sphere_vs_triangle(), rbc::tri::sq_dist_segment_triangle(), rbc::support(), rbc::support(), rbc::CollisionAlgorithm< Box, Box >::test(), rbc::CollisionAlgorithm< Capsule, Capsule >::test(), rbc::CollisionAlgorithm< Capsule, Box >::test(), and rbc::CollisionAlgorithm< Sphere, Capsule >::test().
cross() [1/2]
int m3d::cross (const vec2i & a, const vec2i & b) inline
2D cross product (signed scalar).
Equivalent to the z-component of cross(vec3(a.x,a.y,0), vec3(b.x,b.y,0)). Positive when b is counter-clockwise from a, negative when clockwise.
Definition at line 127 of file vec2i.hpp.
Referenced by rbc::compute_inertia_tensor(), rbc::compute_volume(), rbc::convex_hull_data_create(), rbc::get_generic_face_corners(), rbc::mesh_data_create(), rbc::manifold_detail::reduce_to_4(), m3d::rotate(), rbc::CollisionAlgorithm< Box, Box >::test(), and rbc::CollisionAlgorithm< Capsule, Box >::test().
dot() [2/2]
scalar m3d::dot (const vec3 & a, const vec3 & b) inline
Dot (inner) product of two vectors.
Returns
a.x*b.x + a.y*b.y + a.z*b.z.
Definition at line 146 of file vec3.hpp.
cross() [2/2]
vec3 m3d::cross (const vec3 & a, const vec3 & b) inline
Cross product (a × b), right-handed.
Returns
Vector perpendicular to both a and b.
Definition at line 156 of file vec3.hpp.
length_sq()
scalar m3d::length_sq (const vec3 & v) inline
Squared length of v.
Cheaper than length (no sqrt).
Prefer this for length comparisons (length_sq(a) < r*r).
Definition at line 171 of file vec3.hpp.
Referenced by rbc::tri::capsule_vs_triangle(), rbc::tri::closest_point_on_segment(), m3d::length(), m3d::normalize(), rbc::manifold_detail::reduce_to_4(), rbc::representative_radius(), rbc::tri::sphere_vs_triangle(), rbc::tri::sq_dist_point_triangle(), rbc::tri::sq_dist_segment_triangle(), rbc::CollisionAlgorithm< Capsule, Capsule >::test(), rbc::CollisionAlgorithm< Capsule, Box >::test(), and rbc::CollisionAlgorithm< Sphere, Capsule >::test().
normalize() [2/2]
vec3 m3d::normalize (const vec3 & v) inline
Return v / length(v), or the zero vector if v is near zero.
The zero-length fallback prevents division by zero; callers that need to detect a degenerate input should test length_sq(v) < EPSILON themselves before calling.
Definition at line 197 of file vec3.hpp.
References m3d::EPSILON, m3d::length_sq(), and m3d::sqrt().
Variable Documentation
EPSILON
constexpr scalar m3d::EPSILON = 1e-9 constexpr
Generic small-number tolerance used by is_approx helpers.
Set wider than std::numeric_limits<scalar>::epsilon() so it absorbs the round-off accumulated during physics integration.
Definition at line 49 of file core.hpp.
Referenced by rbc::tri::capsule_vs_triangle(), rbc::tri::closest_point_on_segment(), rbc::compute_inertia_tensor(), rbc::convex_hull_data_create(), m3d::mat3::inverse(), m3d::smat3::inverse(), m3d::normalize(), m3d::normalize(), rbc::tri::sphere_vs_triangle(), rbc::tri::sq_dist_segment_triangle(), rbc::support(), rbc::support(), rbc::support(), rbc::support(), rbc::CollisionAlgorithm< Box, Box >::test(), rbc::CollisionAlgorithm< Capsule, Capsule >::test(), rbc::CollisionAlgorithm< Capsule, Box >::test(), rbc::CollisionAlgorithm< Sphere, Sphere >::test(), rbc::CollisionAlgorithm< Sphere, Box >::test(), and rbc::CollisionAlgorithm< Sphere, Capsule >::test().
ERROR_ULP
constexpr scalar m3d::ERROR_ULP = 2.107342e-08 constexpr
Unit-in-the-Last-Place threshold for double.
Used by quat::normalize to skip the sqrt when the magnitude is already within one ULP of 1.
Definition at line 59 of file core.hpp.