RBPS: rbps — Physics core
rbps — Physics core
Bodies, constraints, joints, contacts, and the World step loop.
Files
file BodyAPI.hpp
Public helpers to add / remove bodies in a BodyCollection.
file ColliderAPI.hpp
Public helpers to add / remove colliders and keep the broad phase in sync.
file ConstraintAPI.hpp
Public helpers for adding / removing constraint rows.
file JointAPI.hpp
Public helpers to create / remove joints (prismatic, revolute, fixed).
file World.hpp
World — the public RBPS facade.
file Body.hpp
BodyCollection SoA + per-body integration / impulse helpers.
file Collider.hpp
ColliderCollection — pure collision layer that owns shapes + materials.
file CollisionPipeline.hpp
Glues rbc (geometry) to rbps (bodies); per-frame contact pipeline.
file Constraint.hpp
Low-level constraint SoA + XPBD impulse computation.
file Contact.hpp
Position-level and velocity-level contact constraint solvers.
file Joint.hpp
Joints (prismatic, revolute, fixed) layered on top of ConstraintCollection.
Classes
struct rbps::BodyParams
Initial properties for a new body.
struct rbps::ColliderParams
Initial properties for a new collider.
struct rbps::ConstraintParams
Parameters for creating a constraint row between two bodies.
struct rbps::PrismaticJointParams
Parameters for create_prismatic_joint.
struct rbps::RevoluteJointParams
Parameters for create_revolute_joint.
struct rbps::FixedJointParams
Parameters for create_fixed_joint.
struct rbps::World
Owns the simulation state and runs the per-frame step loop.
struct rbps::ContactList
Unified SoA carrying the pipeline output AND the solver scratch state.
struct rbps::CollisionPipelineConfig
Tunables for the per-frame collision pipeline.
struct rbps::ConstraintBlock
Stable IDs of the low-level constraint rows that back a joint.
Macros
#define COLLIDER_FIELDS(X)
X-macro field list for ColliderCollection.
Enumerations
enum rbps::BodyType
Motion type of a rigid body.
enum rbps::ConstraintType
Constraint flavour.
enum rbps::JointType
Joint kinematic kind.
enum rbps::JointActuationType
Joint actuation mode.
Functions
uint32_t rbps::create_body (BodyCollection &bc, const BodyParams &params={})
Add a new body to the collection and return its stable ID.
void rbps::remove_body (BodyCollection &bc, uint32_t id)
Remove a body from the collection by stable ID.
bool rbps::shape_bypasses_broadphase (const rbc::Shape &s)
Predicate: shapes whose AABB cannot enter the SAP broad phase.
uint32_t rbps::create_collider (ColliderCollection &cc, rbc::BroadPhaseState &bp, const ColliderParams &p, const m3d::tf &body_world_tf)
Register a collider and (conditionally) insert it into the broad phase.
void rbps::collider_remove (ColliderCollection &cc, rbc::BroadPhaseState &bp, uint32_t id)
Remove a collider and (if it was in the broad phase) unregister it.
uint32_t rbps::create_constraint (ConstraintCollection &cc, const ConstraintParams &params={})
Add a new constraint to the collection.
void rbps::remove_constraint (ConstraintCollection &cc, uint32_t id)
Remove a constraint from the collection.
void rbps::remove_joint (JointCollection &jc, ConstraintCollection &cc, uint32_t id)
Remove a joint and all of its child constraints.
uint32_t rbps::create_prismatic_joint (JointCollection &jc, ConstraintCollection &cc, const PrismaticJointParams &params={})
Create a prismatic (sliding) joint between two bodies.
uint32_t rbps::create_revolute_joint (JointCollection &jc, ConstraintCollection &cc, const RevoluteJointParams &params={})
Create a revolute (hinge) joint between two bodies.
uint32_t rbps::create_fixed_joint (JointCollection &jc, ConstraintCollection &cc, const FixedJointParams &params={})
Create a fixed joint between two bodies (no relative motion).
rbps::DEFINE_DYN_SOA (BodyCollection, uint32_t, 8, BODY_FIELDS) void update_inertia_tensor_world(BodyCollection &bc
Recompute the world-space inertia tensor and its inverse for body i.
void rbps::update_position_and_orientation (BodyCollection &bc, scalar dt)
Integrate positions and orientations for all dynamic bodies.
void rbps::update_velocities (BodyCollection &bc, scalar inv_dt)
Recompute linear and angular velocities from pose deltas.
void rbps::apply_positional_constraint_impulse (BodyCollection &bc, uint32_t i, vec3 impulse, vec3 r)
Apply a positional impulse at offset r to body i.
void rbps::apply_rotational_constraint_impulse (BodyCollection &bc, uint32_t i, vec3 impulse)
Apply a pure rotational impulse to body i.
void rbps::apply_positional_velocity_constraint_impulse (BodyCollection &bc, uint32_t i, vec3 impulse, vec3 r)
Apply a velocity-level impulse at offset r to body i.
void rbps::apply_rotational_velocity_constraint_impulse (BodyCollection &bc, uint32_t i, vec3 impulse)
Apply a velocity-level rotational impulse at to body i.
scalar rbps::get_positional_generalized_inverse_mass (BodyCollection &bc, uint32_t i, vec3 r, vec3 n)
Compute the generalised inverse mass for a positional constraint.
scalar rbps::get_rotational_generalized_inverse_mass (BodyCollection &bc, uint32_t i, vec3 n)
Compute the generalised inverse mass for a rotational constraint.
rbps::DEFINE_DYN_SOA (ColliderCollection, uint32_t, 8, COLLIDER_FIELDS) inline m3d
SoA collection of colliders.
void rbps::update_broad_phase_aabbs (ColliderCollection &cc, rbc::BroadPhaseState &bp, const BodyCollection &bc, m3d::scalar dt, bool use_velocity_expansion)
Step 1 — refresh the broad-phase AABBs.
void rbps::run_collision_pipeline (ColliderCollection &cc, rbc::BroadPhaseState &bp, const BodyCollection &bc, m3d::scalar dt, ContactList &contacts_out, const CollisionPipelineConfig &cfg={})
Steps 2–4 — full pipeline (broad phase → static cull → narrow phase).
void rbps::run_narrow_phase (const rbc::BroadPhaseState &bp, const rbps::ColliderCollection &cc, const BodyCollection &bc, ContactList &out)
Step 2 — narrow-phase pass over the broad-phase pair list.
void rbps::refresh_contacts (ContactList &cl, const BodyCollection &bc)
Step 3 — refresh per-substep contact geometry.
std::vector< std::vector< u_int32_t > > rbps::get_collision_groups (const ContactList &contacts, const BodyCollection &bc)
Greedy graph coloring → independent contact groups for parallel solving.
rbps::DEFINE_DYN_SOA (ConstraintCollection, uint32_t, 8, CONSTRAINT_FIELDS) void set_value(ConstraintCollection &cc
SoA collection of per-constraint data used by the XPBD solver.
scalar rbps::compute_delta_lambda (const ConstraintCollection &cc, uint32_t i, scalar w_1, scalar w_2, scalar inverse_time_step)
Computes the change in the Lagrange multiplier for one constraint.
void rbps::compute_rotational_constraint_impulse (BodyCollection &bc, ConstraintCollection &cc, uint32_t i, scalar inverse_time_step)
Solves and applies a rotational constraint impulse between two bodies.
void rbps::compute_positional_constraint_impulse (BodyCollection &bc, ConstraintCollection &cc, uint32_t i, scalar inverse_time_step)
Solves and applies a rotational constraint impulse between two bodies.
void rbps::reset_lagrange_multiplier (ConstraintCollection &cc, uint32_t i)
Resets the Lagrange multiplier for a given constraint to zero.
void rbps::set_constraint_positions (ConstraintCollection &cc, uint32_t i, const vec3 &r_1, const vec3 &r_2)
Sets the local contact points for a constraint.
scalar rbps::get_lagrange_multiplier (const ConstraintCollection &cc, uint32_t i)
Returns the current Lagrange multiplier λ for a constraint.
scalar rbps::compute_lagrange_multiplier (BodyCollection &bc, ConstraintCollection &cc, uint32_t i, scalar inverse_time_step)
Computes the updated Lagrange multiplier for a single constraint.
void rbps::solve_constraints (BodyCollection &bc, ConstraintCollection &cc, scalar inverse_time_step)
Solves the constraints by computing impulses of the bodies.
void rbps::apply_constraint_position_level (ContactList &cl, uint32_t i, BodyCollection &bc, m3d::scalar inv_h)
Position-level solve for one contact (called every substep).
void rbps::apply_constraint_velocity_level (ContactList &cl, uint32_t i, BodyCollection &bc, m3d::scalar h)
Velocity-level solve for one contact (called once per substep).
void rbps::solve_contacts_position_level (ContactList &cl, BodyCollection &bc, m3d::scalar inv_h)
Iterate apply_constraint_position_level over every contact.
void rbps::solve_contacts_velocity_level (ContactList &cl, BodyCollection &bc, m3d::scalar h)
Iterate apply_constraint_velocity_level over every contact.
rbps::DEFINE_DYN_SOA (JointCollection, uint32_t, 8, JOINT_FIELDS) void compute_prismatic_joint_errors(JointCollection &jc
SoA collection of joints; each row owns up to MAX_CONSTRAINTS_PER_JOINT constraint rows in a ConstraintCollection.
void rbps::compute_revolute_joint_errors (JointCollection &jc, u_int32_t i, BodyCollection &bc, ConstraintCollection &cc, scalar time_step)
Compute the four low-level XPBD constraint errors for a revolute joint.
void rbps::compute_fixed_joint_errors (JointCollection &jc, u_int32_t i, BodyCollection &bc, ConstraintCollection &cc, scalar)
Compute the two low-level XPBD constraint errors for a fixed joint.
void rbps::apply_prismatic_joint_damping (JointCollection &jc, u_int32_t i, BodyCollection &bc, scalar time_step)
Applies damping impulses to a primsatic joint by resisting relative linear motion.
void rbps::apply_revolute_joint_damping (JointCollection &jc, u_int32_t i, BodyCollection &bc, scalar time_step)
Applies angular damping to a revolute joint to resist relative rotation.
void rbps::compute_joint_errors (JointCollection &jc, BodyCollection &bc, ConstraintCollection &cc, scalar time_step)
Computes joint errors.
void rbps::apply_joint_damping (JointCollection &jc, BodyCollection &bc, scalar time_step)
Applies joint damping to all the joints.
Detailed Description
Bodies, constraints, joints, contacts, and the World step loop.
The user-facing entry point is World in API/World.hpp. Lower-level layers (Body / Constraint / Joint / Contact / Collider) are exposed for fine-grained control or for unit-tested data flow.
Step loop summary
Per frame: broad-phase update → narrow-phase contact detection → N substeps of (integrate → position-level solve → velocity update → velocity-level solve). See API/World.hpp for the full diagram.
Macro Definition Documentation
COLLIDER_FIELDS
#define COLLIDER_FIELDS (X)
Value:
    X(rbc::Shape, shape)            \
    X(m3d::vec3, local_pos)         \
    X(m3d::quat, local_rot)         \
    X(uint32_t, body_id)            \
    X(rbc::BPHandle, bp_handle)     \
    X(bool, is_static)              \
    X(m3d::scalar, restitution)     \
    X(m3d::scalar, static_friction) \
    X(m3d::scalar, dynamic_friction)
X-macro field list for ColliderCollection.
Add new per-collider data here; DEFINE_DYN_SOA derives all bookkeeping automatically.
Definition at line 43 of file Collider.hpp.
Enumeration Type Documentation
BodyType
enum rbps::BodyType
Motion type of a rigid body.
STATIC — infinite mass; never moved by the solver. Used for level geometry, anchors, and kinematic obstacles.
DYNAMIC — integrated each frame; affected by forces, torques, and constraint impulses.
Definition at line 41 of file Body.hpp.
ConstraintType
enum rbps::ConstraintType
Constraint flavour.
POSITIONAL — couples translation: enforces a vector relationship between two attachment points.
ROTATIONAL — couples orientation: enforces an axis or angle relationship between two body frames.
Definition at line 25 of file Constraint.hpp.
JointType
enum rbps::JointType
Joint kinematic kind.
PRISMATIC — sliding along an axis, no relative rotation.
REVOLUTE — rotation about an axis (hinge), no relative translation.
FIXED — no relative motion at all.
Definition at line 31 of file Joint.hpp.
JointActuationType
enum rbps::JointActuationType
Joint actuation mode.
FREE — no driver; the joint is purely passive.
POSITION — driver follows target_position.
SPEED — driver follows target_speed (target_position is advanced by speed*dt each frame).
Definition at line 48 of file Joint.hpp.
Function Documentation
create_body()
uint32_t rbps::create_body (BodyCollection & bc, const BodyParams & params = {}) inline
Add a new body to the collection and return its stable ID.
The SoA allocates the slot and zero-initialises all fields first. This function then writes the caller-supplied parameter values. Gravity is baked into the initial force vector.
Parameters
bc The BodyCollection.
params Initial body properties (all have defaults).
Returns
Stable ID — safe to store long-term. Use bc.index_of(id) to get the current packed array index.
Example
uint32_t ball = create_body(bc, { .mass=2.0, .position={0,5,0} });
uint32_t i    = bc.index_of(ball);    // packed index for direct array access
Definition at line 53 of file BodyAPI.hpp.
Referenced by rbps::World::create_body().
remove_body()
void rbps::remove_body (BodyCollection & bc, uint32_t id) inline
Remove a body from the collection by stable ID.
Uses swap-and-pop internally: the last live body slides into the freed slot so all other IDs and packed indices are unaffected except for the item that was last (its packed index changes).
Passing a stale or never-issued ID is safe — it is silently ignored.
Parameters
bc The BodyCollection.
id Stable ID returned by create_body().
Definition at line 96 of file BodyAPI.hpp.
shape_bypasses_broadphase()
bool rbps::shape_bypasses_broadphase (const rbc::Shape & s) inline
Predicate: shapes whose AABB cannot enter the SAP broad phase.
Plane has an infinite AABB and is handled by a dedicated loop in run_narrow_phase (planes are tested against every dynamic collider). Heightmap follows the same pattern once its dispatch is wired up.
Definition at line 39 of file ColliderAPI.hpp.
References rbc::Shape::is().
Referenced by create_collider().
create_collider()
uint32_t rbps::create_collider (ColliderCollection & cc, rbc::BroadPhaseState & bp, const ColliderParams & p, const m3d::tf & body_world_tf) inline
Register a collider and (conditionally) insert it into the broad phase.
Planes and other infinite shapes skip broad-phase insertion entirely and receive BP_INVALID_HANDLE; the collision pipeline handles them in a dedicated loop inside run_narrow_phase.
Parameters
cc The collider collection.
bp Broad-phase state to update.
p Collider properties.
body_world_tf World transform of the owning body, used to compute the initial AABB.
Returns
Stable uint32_t ID of the new collider.
Definition at line 61 of file ColliderAPI.hpp.
References rbps::ColliderParams::body_id, rbc::broad_phase_insert(), rbc::compute_aabb(), rbps::ColliderParams::dynamic_friction, rbps::ColliderParams::is_static, rbps::ColliderParams::local_pos, rbps::ColliderParams::local_rot, m3d::tf::pos, rbps::ColliderParams::restitution, m3d::tf::rot, m3d::rotate(), rbps::ColliderParams::shape, shape_bypasses_broadphase(), and rbps::ColliderParams::static_friction.
Referenced by rbps::World::create_collider().
create_constraint()
uint32_t rbps::create_constraint (ConstraintCollection & cc, const ConstraintParams & params = {}) inline
Add a new constraint to the collection.
Parameters
cc The ConstraintCollection.
params Constraint properties.
Returns
Stable uint32_t ID of the new constraint, which can be used to reference it later.
Definition at line 37 of file ConstraintAPI.hpp.
Referenced by rbps::World::create_constraint().
remove_constraint()
void rbps::remove_constraint (ConstraintCollection & cc, uint32_t id) inline
Remove a constraint from the collection.
Uses swap-and-pop: the last constraint slides into the freed slot so all other IDs remain valid. Any Handle to this ID becomes false after this call.
Parameters
cc The ConstraintCollection.
id Stable ID returned by create_constraint().
Definition at line 77 of file ConstraintAPI.hpp.
remove_joint()
void rbps::remove_joint (JointCollection & jc, ConstraintCollection & cc, uint32_t id) inline
Remove a joint and all of its child constraints.
Child constraints are removed in reverse order so that each swap-and-pop inside remove_constraint does not disturb the IVC IDs of the siblings that are still pending removal.
Order of operations:
Read constraint_start / constraint_count from the joint (while still valid).
Remove child constraints last-to-first.
Remove the joint itself.
Parameters
jc The JointCollection.
cc The ConstraintCollection that owns the child constraints.
id Stable ivc::ID of the joint to remove.
Definition at line 113 of file JointAPI.hpp.
create_prismatic_joint()
uint32_t rbps::create_prismatic_joint (JointCollection & jc, ConstraintCollection & cc, const PrismaticJointParams & params = {}) inline
Create a prismatic (sliding) joint between two bodies.
Child constraints in cc: [start+0] ROTATIONAL — full orientation lock [start+1] POSITIONAL — attachment-point lock (perpendicular to axis) [start+2] POSITIONAL — drive / limit along the axis (carries compliance)
Returns
Stable ivc::ID of the joint.
Definition at line 191 of file JointAPI.hpp.
Referenced by rbps::World::create_prismatic_joint().
create_revolute_joint()
uint32_t rbps::create_revolute_joint (JointCollection & jc, ConstraintCollection & cc, const RevoluteJointParams & params = {}) inline
Create a revolute (hinge) joint between two bodies.
Child constraints in cc: [start+0] ROTATIONAL — axis alignment [start+1] POSITIONAL — attachment-point lock [start+2] ROTATIONAL — angle limit [start+3] ROTATIONAL — drive (carries compliance)
Returns
Stable ivc::ID of the joint.
Definition at line 223 of file JointAPI.hpp.
Referenced by rbps::World::create_revolute_joint().
create_fixed_joint()
uint32_t rbps::create_fixed_joint (JointCollection & jc, ConstraintCollection & cc, const FixedJointParams & params = {}) inline
Create a fixed joint between two bodies (no relative motion).
Child constraints in cc: [start+0] ROTATIONAL — full orientation lock [start+1] POSITIONAL — attachment-point lock
Returns
Stable uint32_t (id) of the joint.
Definition at line 253 of file JointAPI.hpp.
Referenced by rbps::World::create_fixed_joint().
DEFINE_DYN_SOA() [1/4]
rbps::DEFINE_DYN_SOA (BodyCollection , uint32_t , 8 , BODY_FIELDS) &
Recompute the world-space inertia tensor and its inverse for body i.
Must be called whenever orientation[i] changes before any function that reads inertia_tensor_world or inverse_inertia_tensor_world.
Parameters
bc The BodyCollection.
i Packed data index of the body to update.
update_position_and_orientation()
void rbps::update_position_and_orientation (BodyCollection & bc, scalar dt)
Integrate positions and orientations for all dynamic bodies.
For each dynamic body:
Store previous pose.
Recompute world inertia tensor.
Integrate linear velocity from applied forces.
Integrate position.
Integrate angular velocity from applied torques (gyroscopic correction).
Update orientation via small-angle quaternion approximation.
Parameters
bc The BodyCollection.
dt Time step (Δt).
Referenced by rbps::World::step().
update_velocities()
void rbps::update_velocities (BodyCollection & bc, scalar inv_dt)
Recompute linear and angular velocities from pose deltas.
Called after constraint solving to derive post-solve velocities.
Parameters
bc The BodyCollection.
inv_dt Inverse time step (1/Δt).
Referenced by rbps::World::step().
apply_positional_constraint_impulse()
void rbps::apply_positional_constraint_impulse (BodyCollection & bc, uint32_t i, vec3 impulse, vec3 r)
Apply a positional impulse at offset r to body i.
Adjusts position and orientation. Used during position-level constraint solving (XPBD).
Parameters
bc The BodyCollection.
i Packed data index.
impulse Impulse vector in world space.
r Lever arm from centre of mass to application point (world space).
apply_rotational_constraint_impulse()
void rbps::apply_rotational_constraint_impulse (BodyCollection & bc, uint32_t i, vec3 impulse)
Apply a pure rotational impulse to body i.
Parameters
bc The BodyCollection.
i Packed data index.
impulse Rotational impulse (torque impulse) in world space.
apply_positional_velocity_constraint_impulse()
void rbps::apply_positional_velocity_constraint_impulse (BodyCollection & bc, uint32_t i, vec3 impulse, vec3 r)
Apply a velocity-level impulse at offset r to body i.
Adjusts linear_velocity and angular_velocity. Used during velocity-level constraint solving (restitution, friction). No-op if the body is STATIC.
Parameters
bc The BodyCollection.
i Packed data index.
impulse Impulse vector in world space.
r Lever arm from centre of mass to application point (world space).
Referenced by visr::dispatch_command().
apply_rotational_velocity_constraint_impulse()
void rbps::apply_rotational_velocity_constraint_impulse (BodyCollection & bc, uint32_t i, vec3 impulse)
Apply a velocity-level rotational impulse at to body i.
Adjusts angular_velocity. Used during velocity-level joint damping solver. No-op if the body is STATIC.
Parameters
bc The BodyCollection.
i Packed data index.
impulse Impulse vector in world space.
get_positional_generalized_inverse_mass()
scalar rbps::get_positional_generalized_inverse_mass (BodyCollection & bc, uint32_t i, vec3 r, vec3 n)
Compute the generalised inverse mass for a positional constraint.
Returns w = 1/m + (r×n)ᵀ I⁻¹ (r×n). Returns 0 for STATIC bodies.
Parameters
bc The BodyCollection.
i Packed data index.
r Vector from centre of mass to contact point.
n Constraint direction (unit normal).
Returns
Generalised inverse mass scalar.
get_rotational_generalized_inverse_mass()
scalar rbps::get_rotational_generalized_inverse_mass (BodyCollection & bc, uint32_t i, vec3 n)
Compute the generalised inverse mass for a rotational constraint.
Returns w = nᵀ I⁻¹ n. Returns 0 for STATIC bodies.
Parameters
bc The BodyCollection.
i Packed data index.
n Rotation axis (unit direction).
Returns
Generalised inverse mass scalar.
DEFINE_DYN_SOA() [2/4]
rbps::DEFINE_DYN_SOA (ColliderCollection , uint32_t , 8 , COLLIDER_FIELDS)
SoA collection of colliders.
Use ColliderAPI to add/remove safely.
Each row pairs a rbc::Shape with a body-local pose offset, a broad-phase handle, and material parameters used by the contact solver. Shapes that bypass the broad phase (e.g. Plane) carry BP_INVALID_HANDLE and are dispatched separately.
Compute the world transform for the collider at slot idx.
Composes the body's world pose with the collider's body-local offset: world_tf = (body_pos + body_rot * local_pos, body_rot * local_rot).
Definition at line 63 of file Collider.hpp.
References m3d::rotate().
update_broad_phase_aabbs()
void rbps::update_broad_phase_aabbs (ColliderCollection & cc, rbc::BroadPhaseState & bp, const BodyCollection & bc, m3d::scalar dt, bool use_velocity_expansion)
Step 1 — refresh the broad-phase AABBs.
Static colliders are inserted once at startup and never moved. Dynamic colliders are updated every tick, optionally with velocity-swept AABB expansion (use_velocity_expansion).
Referenced by rbps::World::step().
run_collision_pipeline()
void rbps::run_collision_pipeline (ColliderCollection & cc, rbc::BroadPhaseState & bp, const BodyCollection & bc, m3d::scalar dt, ContactList & contacts_out, const CollisionPipelineConfig & cfg = {})
Steps 2–4 — full pipeline (broad phase → static cull → narrow phase).
Clears and refills contacts_out each call.
run_narrow_phase()
void rbps::run_narrow_phase (const rbc::BroadPhaseState & bp, const rbps::ColliderCollection & cc, const BodyCollection & bc, ContactList & out)
Step 2 — narrow-phase pass over the broad-phase pair list.
Runs GJK/EPA (or analytic algorithms via the dispatcher) for each candidate pair, emits ContactList rows with body-LOCAL lever arms and zero lambdas. Does NOT fill the world-space substep data — that is done by refresh_contacts at the start of each substep.
Referenced by rbps::World::step().
refresh_contacts()
void rbps::refresh_contacts (ContactList & cl, const BodyCollection & bc)
Step 3 — refresh per-substep contact geometry.
Reconstructs world-space contact points from stored body-LOCAL lever arms and the bodies' current transforms. Updates point_on_a, point_on_b, and penetration_depth. Does NOT touch the lambdas.
Implements eq. (26) of Müller et al. (XPBD):
p1 = x1 + rotate(q1, r1_local)
p2 = x2 + rotate(q2, r2_local)
d = dot(p1 - p2, n)
get_collision_groups()
std::vector< std::vector< u_int32_t > > rbps::get_collision_groups (const ContactList & contacts, const BodyCollection & bc)
Greedy graph coloring → independent contact groups for parallel solving.
Each returned inner vector contains contact indices that share NO body in common, so they can be solved in parallel. Algorithm: O(n + e) greedy coloring where contacts are nodes and edges connect contacts that share a body. Each color = one solve wave.
Call after run_collision_pipeline / run_narrow_phase.
DEFINE_DYN_SOA() [3/4]
rbps::DEFINE_DYN_SOA (ConstraintCollection , uint32_t , 8 , CONSTRAINT_FIELDS) &
SoA collection of per-constraint data used by the XPBD solver.
Holds every data array needed to evaluate and apply constraint impulses between pairs of bodies. Joints are built on top of this collection (one row per low-level constraint they generate).
Computes and stores magnitude and direction for a raw constraint vector.
Parameters
cc The ConstraintCollection to update.
i Index of the constraint.
value Raw 3D vector whose magnitude/direction to extract.
compute_delta_lambda()
scalar rbps::compute_delta_lambda (const ConstraintCollection & cc, uint32_t i, scalar w_1, scalar w_2, scalar inverse_time_step)
Computes the change in the Lagrange multiplier for one constraint.
Implements: Δλ = (–b – α·λ_old) / (w₁ + w₂ + α)
Parameters
cc The ConstraintCollection.
i Index of the constraint.
w_1 Generalized inverse mass of body 1.
w_2 Generalized inverse mass of body 2.
inverse_time_step Inverse of the time step (1/Δt).
Returns
Change in Lagrange multiplier Δλ.
compute_rotational_constraint_impulse()
void rbps::compute_rotational_constraint_impulse (BodyCollection & bc, ConstraintCollection & cc, uint32_t i, scalar inverse_time_step)
Solves and applies a rotational constraint impulse between two bodies.
Computes generalized inverse masses for each body about the constraint axis.
Computes Δλ and updates the constraint’s λ.
Converts Δλ into an impulse and corresponding torque.
Applies equal-and-opposite rotational impulses to each body.
Parameters
bc The BodyCollection containing all bodies.
cc The ConstraintCollection.
i Index of the constraint.
inverse_time_step Inverse of the time step (1/Δt).
compute_positional_constraint_impulse()
void rbps::compute_positional_constraint_impulse (BodyCollection & bc, ConstraintCollection & cc, uint32_t i, scalar inverse_time_step)
Solves and applies a rotational constraint impulse between two bodies.
Computes generalized inverse masses for each body about the constraint axis.
Computes Δλ and updates the constraint’s λ.
Converts Δλ into an impulse and corresponding torque.
Applies equal-and-opposite rotational impulses to each body.
Parameters
bc The BodyCollection containing all bodies.
cc The ConstraintCollection.
i Index of the constraint.
inverse_time_step Inverse of the time step (1/Δt).
reset_lagrange_multiplier()
void rbps::reset_lagrange_multiplier (ConstraintCollection & cc, uint32_t i)
Resets the Lagrange multiplier for a given constraint to zero.
Parameters
cc The ConstraintCollection.
i Index of the constraint to reset.
set_constraint_positions()
void rbps::set_constraint_positions (ConstraintCollection & cc, uint32_t i, const vec3 & r_1, const vec3 & r_2)
Sets the local contact points for a constraint.
Parameters
cc The ConstraintCollection.
i Index of the constraint.
r_1 Local contact point on body 1.
r_2 Local contact point on body 2.
get_lagrange_multiplier()
scalar rbps::get_lagrange_multiplier (const ConstraintCollection & cc, uint32_t i)
Returns the current Lagrange multiplier λ for a constraint.
Parameters
cc The ConstraintCollection.
i Index of the constraint.
Returns
Current λ value.
compute_lagrange_multiplier()
scalar rbps::compute_lagrange_multiplier (BodyCollection & bc, ConstraintCollection & cc, uint32_t i, scalar inverse_time_step)
Computes the updated Lagrange multiplier for a single constraint.
Does not store the result—returns λ_old + Δλ based on current state.
Parameters
bc The BodyCollection.
cc The ConstraintCollection.
i Index of the constraint.
inverse_time_step Inverse of the time step (1/Δt).
Returns
Updated Lagrange multiplier.
solve_constraints()
void rbps::solve_constraints (BodyCollection & bc, ConstraintCollection & cc, scalar inverse_time_step)
Solves the constraints by computing impulses of the bodies.
Parameters
bc The BodyCollection containing all bodies.
cc The ConstraintCollection containing all constraints.
inverse_time_step Inverse of the time step (1/Δt).
Referenced by rbps::World::solve_positions().
apply_constraint_position_level()
void rbps::apply_constraint_position_level (ContactList & cl, uint32_t i, BodyCollection & bc, m3d::scalar inv_h)
Position-level solve for one contact (called every substep).
Steps:
Re-check penetration depth along the normal using current positions. If the bodies have separated, sets collision[i] = false and exits.
Records the pre-solve normal relative velocity in relative_velocity[i] (used later by the velocity-level solver for restitution).
Delegates to solve_normal_constraint and solve_tangent_constraint.
apply_constraint_velocity_level()
void rbps::apply_constraint_velocity_level (ContactList & cl, uint32_t i, BodyCollection & bc, m3d::scalar h)
Velocity-level solve for one contact (called once per substep).
Applies restitution along the normal and dynamic Coulomb friction in the tangential plane. Uses relative_velocity[i] captured at position-solve time as the pre-collision velocity for the restitution coefficient.
DEFINE_DYN_SOA() [4/4]
rbps::DEFINE_DYN_SOA (JointCollection , uint32_t , 8 , JOINT_FIELDS) &
SoA collection of joints; each row owns up to MAX_CONSTRAINTS_PER_JOINT constraint rows in a ConstraintCollection.
Compute the three low-level XPBD constraint errors for a prismatic joint.
For joint i:
Computes the rotational alignment error between body orientations.
Computes the positional attachment-point error along the sliding axis, including limit overshoot correction if enabled.
Computes the drive error based on actuation type (FREE, SPEED, POSITION).
FREE: zero error
SPEED: advance target_position by speed*dt, then fall through
POSITION: error to target_position
The errors are stored into the global ConstraintCollection at indices [start+0..start+2]. Also updates jc.current_position[i] to the raw slide distance.
Parameters
jc The JointCollection containing prismatic joint data.
i Index of the prismatic joint to process.
bc The BodyCollection holding all body transforms.
cc The global ConstraintCollection for low-level constraints.
time_step The simulation time step Δt.
compute_revolute_joint_errors()
void rbps::compute_revolute_joint_errors (JointCollection & jc, u_int32_t i, BodyCollection & bc, ConstraintCollection & cc, scalar time_step)
Compute the four low-level XPBD constraint errors for a revolute joint.
For joint i:
Rotational alignment error of the main axis.
Positional attachment-point error.
Rotational angle-limit error (clamped if limited).
Rotational drive error based on actuation type (FREE, SPEED, POSITION).
The errors are stored into the global ConstraintCollection at indices [start+0..start+3]. Also updates jc.current_position[i] to the current joint angle φ.
Parameters
jc The JointCollection containing revolute joint data.
i Index of the revolute joint to process.
bc The BodyCollection holding all body transforms.
cc The global ConstraintCollection for low-level constraints.
time_step The simulation time step Δt.
compute_fixed_joint_errors()
void rbps::compute_fixed_joint_errors (JointCollection & jc, u_int32_t i, BodyCollection & bc, ConstraintCollection & cc, scalar)
Compute the two low-level XPBD constraint errors for a fixed joint.
For joint i:
Rotational alignment error between body orientations.
Positional attachment-point error.
The errors are stored into the global ConstraintCollection at indices [start+0..start+1].
Parameters
jc The JointCollection containing fixed joint data.
i Index of the fixed joint to process.
bc The BodyCollection holding all body transforms.
cc The global ConstraintCollection for low-level constraints.
time_step The simulation time step Δt (unused for fixed joints).
apply_prismatic_joint_damping()
void rbps::apply_prismatic_joint_damping (JointCollection & jc, u_int32_t i, BodyCollection & bc, scalar time_step)
Applies damping impulses to a primsatic joint by resisting relative linear motion.
Computes a corrective impulse based on the relative linear velocity between the two bodies connected by joint i, scaled by the joint’s damping coefficient. This impulse is applied as a positional‐velocity‐level constraint at each body’s attachment point to dissipate energy and simulate viscous damping.
Steps:
Compute Δv = (v₂ − v₁) * min(damping * Δt, 1).
If ‖Δv‖ < EPSILON, exit early (no significant relative motion).
Calculate world‐space attachment points r₁, r₂.
Normalize n = Δv / ‖Δv‖.
Compute each body’s generalized inverse mass along n.
Compute impulse = Δv / (w₁ + w₂).
Apply equal-and-opposite velocity impulses at r₁ and r₂.
Parameters
jc The JointCollection containing damping parameters.
i Index of the joint to apply damping for.
bc The BodyCollection holding body velocities and inverses.
time_step Simulation time step Δt.
apply_revolute_joint_damping()
void rbps::apply_revolute_joint_damping (JointCollection & jc, u_int32_t i, BodyCollection & bc, scalar time_step)
Applies angular damping to a revolute joint to resist relative rotation.
Computes and applies an angular damping impulse based on the difference in angular velocity between two connected bodies. This simulates viscous resistance around the joint’s axis and helps stabilize the simulation.
Steps:
Compute Δω = (ω₂ − ω₁) * min(damping * Δt, 1).
Apply +Δω to body 1 and −Δω to body 2.
Parameters
jc The JointCollection with damping values.
i Index of the revolute joint.
bc The BodyCollection holding angular velocities.
time_step Simulation timestep Δt.
compute_joint_errors()
void rbps::compute_joint_errors (JointCollection & jc, BodyCollection & bc, ConstraintCollection & cc, scalar time_step)
Computes joint errors.
This function calculates the errors for each joint contraint The errors represent the degree to which the joint constraints are violated. These errors are then used to apply corrective impulses to satisfy the constraints.
Parameters
jc JointCollection reference
bc BodyCollection
cc ConstraintCollection
time_step timestep
Referenced by rbps::World::solve_positions().
apply_joint_damping()
void rbps::apply_joint_damping (JointCollection & jc, BodyCollection & bc, scalar time_step)
Applies joint damping to all the joints.
Parameters
jc JointCollection reference
bc BodyCollection reference
time_step timestep
Referenced by rbps::World::solve_velocities().