RBPS: rbc — Rigid-Body Collision
rbc — Rigid-Body Collision
Collision shapes, broad-phase, narrow-phase, GJK/EPA, and contact manifolds.
Files
file AABB.hpp
Axis-aligned bounding box and utility free functions.
file BoxBox.hpp
Analytic Box–Box collision algorithm (SAT + face/face manifold).
file CapsuleBox.hpp
Analytic Capsule–Box collision algorithm (SAT).
file CapsuleCapsule.hpp
Analytic Capsule–Capsule collision algorithm.
file HeightmapCollision.hpp
Analytic shape–Heightmap collision algorithms.
file MeshCollision.hpp
Analytic shape–Mesh collision algorithms.
file PlaneCollision.hpp
Analytic convex-shape-vs-Plane collision algorithms.
file SphereBox.hpp
Analytic Sphere–Box collision algorithm.
file SphereCapsule.hpp
Analytic Sphere–Capsule collision algorithm.
file SphereSphere.hpp
Analytic Sphere–Sphere collision algorithm.
file TriangleUtils.hpp
Triangle/segment geometry helpers shared by mesh + heightmap collision.
file BroadPhase.hpp
Sweep-and-Prune (SAP) broad-phase data structures and API.
file Contact.hpp
ContactPoint and ContactManifold — the output of every collision query.
file Dispatcher.hpp
Compile-time dispatch from (Shape, Shape) to the right collision algorithm.
file ContactManifoldGenerator.hpp
Build a 1–4 point contact manifold from a single EPA result.
file EPA.hpp
Expanding Polytope Algorithm — penetration depth and normal recovery.
file GJK.hpp
Gilbert–Johnson–Keerthi algorithm — overlap test for convex shapes.
file MinkowskiDiff.hpp
Implicit Minkowski difference A ⊖ B used by GJK and EPA.
file narrow_phase.hpp
Public entry point for narrow-phase collision queries.
file Box.hpp
Oriented box (OBB) collision shape.
file Capsule.hpp
Capsule (line segment with spherical caps) collision shape.
file Cone.hpp
Right circular cone collision shape.
file ConvexHull.hpp
Convex polytope collision shape.
file Cylinder.hpp
Cylinder collision shape.
file Ellipsoid.hpp
Ellipsoid collision shape.
file FaceHelpers.hpp
Disc-approximation fallback for shapes without flat faces.
file Heightmap.hpp
Heightmap (terrain grid) collision shape.
file Mesh.hpp
Triangle-mesh collision shape (general — concave allowed).
file Plane.hpp
Infinite half-space (plane) collision shape.
file ShapeTypes.hpp
Shape variant + variant-level dispatchers (compute_aabb, shape_support, shape_face_corners, shape_representative_radius).
file Sphere.hpp
Sphere collision shape.
Classes
struct rbc::AABB
Axis-Aligned Bounding Box stored as min/max corners in world space.
struct rbc::CollisionAlgorithm< Box, Box >
Box vs Box via 15-axis SAT; produces a face/face manifold (1–4 contacts).
struct rbc::CollisionAlgorithm< Capsule, Box >
Capsule vs Box via SAT on 6 axes; 1 or 2 contacts depending on the feature.
struct rbc::CollisionAlgorithm< Box, Capsule >
Box vs Capsule — reuses <Capsule, Box> and flips the normal.
struct rbc::CollisionAlgorithm< Capsule, Capsule >
Capsule vs Capsule via segment-segment closest-points; 1 or 2 contacts.
struct rbc::CollisionAlgorithm< Sphere, Box >
Closest-point analytic test for sphere vs OBB; produces 1 contact point.
struct rbc::CollisionAlgorithm< Box, Sphere >
Box vs Sphere — reuses <Sphere, Box> and flips the normal.
struct rbc::CollisionAlgorithm< Sphere, Capsule >
Sphere vs Capsule via segment-distance reduction; 1 contact point.
struct rbc::CollisionAlgorithm< Capsule, Sphere >
Capsule vs Sphere — reuses <Sphere, Capsule> and flips the normal.
struct rbc::CollisionAlgorithm< Sphere, Sphere >
Distance test: overlap iff |center_b - center_a| < r_a + r_b.
struct rbc::BroadPhasePair
A pair of user IDs that the broad phase flagged as potentially overlapping.
struct rbc::SAPEndpoint
Internal: one sorted endpoint per AABB edge on the projection axis.
struct rbc::BPObject
Internal: per-registered-object record stored in BroadPhaseState::objects.
struct rbc::BroadPhaseConfig
Broad-phase tuning parameters.
struct rbc::BroadPhaseState
All state owned by the broad phase.
struct rbc::ContactPoint
A single contact point: world-space position and penetration depth.
struct rbc::ContactManifold
Up to 4 contact points sharing a single normal (the "manifold").
struct rbc::CollisionAlgorithm< A, B >
Primary template: GJK + EPA + manifold generation for convex pairs.
struct rbc::CollisionAlgorithmSym< A, B >
Symmetric helper: (B, A) reuses (A, B) and flips the contact normal.
struct rbc::MinkowskiDiff
Minkowski difference of two shapes, accessed only through its support function.
struct rbc::Box
Oriented box, defined by its half-extents along the body's local axes.
struct rbc::Capsule
Capsule = a Y-axis cylinder of radius radius capped with two hemispheres.
struct rbc::Cone
Right circular cone aligned with local +Y.
struct rbc::ConvexHullData
Backing storage for a convex polytope in local space.
struct rbc::ConvexHull
Convex hull shape — wraps a non-owning pointer to ConvexHullData.
struct rbc::Cylinder
Cylinder aligned with local +Y.
struct rbc::Ellipsoid
Axis-aligned ellipsoid in local space.
struct rbc::HeightmapData
Backing storage for a row-major grid of height samples.
struct rbc::Heightmap
Heightmap shape — wraps a non-owning pointer to HeightmapData.
struct rbc::MeshData
Backing storage for a triangle mesh in local space.
struct rbc::Mesh
Mesh shape — wraps a non-owning pointer to MeshData.
struct rbc::Plane
Infinite half-space defined by normal · x = d in local space.
struct rbc::Shape
Type-erased collision shape: a std::variant over every concrete shape.
struct rbc::Sphere
Sphere of given radius, centred on the body's transform origin.
Typedefs
using rbc::BPHandle = uint32_t
Opaque handle for a registered broad-phase object.
Functions
bool rbc::aabb_overlap (const AABB &a, const AABB &b)
Test whether two AABBs overlap (separating-axis test on all 3 axes).
AABB rbc::aabb_union (const AABB &a, const AABB &b)
Smallest AABB enclosing both a and b.
AABB rbc::aabb_expand (const AABB &a, m3d::scalar margin)
Expand the AABB by a uniform margin on all sides.
m3d::vec3 rbc::aabb_center (const AABB &a)
Geometric centre of the AABB.
m3d::vec3 rbc::aabb_half_extents (const AABB &a)
Half-extents (max - min) / 2.
m3d::scalar rbc::aabb_surface_area (const AABB &a)
Surface area of the AABB.
void rbc::broad_phase_init (BroadPhaseState &bp, const BroadPhaseConfig &cfg=BroadPhaseConfig{})
Initialise a BroadPhaseState with the given config.
BPHandle rbc::broad_phase_insert (BroadPhaseState &bp, uint32_t user_id, const AABB &tight_aabb)
Register a new object.
void rbc::broad_phase_remove (BroadPhaseState &bp, BPHandle h)
Unregister an object.
void rbc::broad_phase_move (BroadPhaseState &bp, BPHandle h, const AABB &new_tight_aabb)
Notify the broad phase that an object has moved.
void rbc::broad_phase_update (BroadPhaseState &bp)
Run the broad phase.
void rbc::broad_phase_move_shape (BroadPhaseState &bp, BPHandle h, const Shape &shape, const m3d::tf &tf)
Convenience: compute an AABB from (shape, tf) and call broad_phase_move.
void rbc::broad_phase_move_swept (BroadPhaseState &bp, BPHandle h, const AABB &tight_aabb, const m3d::vec3 &linear_velocity, m3d::scalar dt)
Velocity-expanded move (anti-tunnelling).
void rbc::broad_phase_move_shape_swept (BroadPhaseState &bp, BPHandle h, const Shape &shape, const m3d::tf &tf, const m3d::vec3 &linear_velocity, m3d::scalar dt)
Convenience: shape + transform + velocity sweep.
bool rbc::test_narrow_phase (const Shape &shape_a, const m3d::tf &tf_a, const Shape &shape_b, const m3d::tf &tf_b, rbc::ContactManifold &manifold)
Test a single shape pair and fill a ContactManifold on overlap.
m3d::vec3 rbc::support (const Box &box, const m3d::vec3 &dir)
Local-space support: corner whose components match the sign of dir.
m3d::scalar rbc::compute_volume (const Box &box)
Box volume 8·hx·hy·hz.
m3d::smat3 rbc::compute_inertia_tensor (const Box &box)
Inertia tensor of a uniform-density box about its centre.
AABB rbc::compute_aabb (const Box &b, const m3d::tf &tf)
Tight world AABB of an oriented box.
constexpr bool rbc::is_gjk_convex (const Box *)
Tag-dispatched marker: Box is a convex bounded shape (true).
m3d::scalar rbc::representative_radius (const Box &b)
Representative size = the largest half-extent.
int rbc::face_corners (const Box &b, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *corners, int capacity)
4 corners of the box face whose outward normal is most aligned with dir.
void rbc::capsule_endpoints (const Capsule &c, const m3d::tf &tf, m3d::vec3 &p1_out, m3d::vec3 &p2_out)
World-space endpoints of the capsule's central segment.
m3d::vec3 rbc::support (const Capsule &c, const m3d::vec3 &dir)
Local-space support: pick the cap centre on the side dir.y points to, then nudge by radius * normalize(dir).
m3d::scalar rbc::compute_volume (const Capsule &c)
Volume = cylinder + two hemispheres = π·r²·(2h + 4r/3).
m3d::smat3 rbc::compute_inertia_tensor (const Capsule &c)
Inertia tensor of a uniform-density capsule about its centre.
AABB rbc::compute_aabb (const Capsule &c, const m3d::tf &tf)
Tight world AABB.
constexpr bool rbc::is_gjk_convex (const Capsule *)
Tag-dispatched marker: Capsule is a convex bounded shape (true).
m3d::scalar rbc::representative_radius (const Capsule &c)
Representative size = the cap radius.
int rbc::face_corners (const Capsule &c, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
Disc-approximation face polygon (capsule has no flat face).
m3d::vec3 rbc::support (const Cone &c, const m3d::vec3 &dir)
Local-space support — pick the apex or a point on the base circle.
m3d::scalar rbc::compute_volume (const Cone &c)
Volume (1/3)·π·r²·h_total.
m3d::smat3 rbc::compute_inertia_tensor (const Cone &c)
Inertia tensor of a uniform-density cone about its centre.
AABB rbc::compute_aabb (const Cone &c, const m3d::tf &tf)
Tight world AABB via 6-direction support sweep.
constexpr bool rbc::is_gjk_convex (const Cone *)
Tag-dispatched marker: Cone is a convex bounded shape (true).
m3d::scalar rbc::representative_radius (const Cone &c)
Representative size = max(base_radius, half_height).
int rbc::face_corners (const Cone &c, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
Disc-approximation face polygon (cone has no flat side face).
ConvexHullData * rbc::convex_hull_data_create (const m3d::vec3 *vertices, uint32_t vert_count, const uint32_t *face_indices=nullptr, uint32_t face_count=0)
Allocate a ConvexHullData and precompute face normals + local AABB.
void rbc::convex_hull_data_destroy (ConvexHullData *hd)
Free a ConvexHullData returned by convex_hull_data_create.
m3d::vec3 rbc::support (const ConvexHull &h, const m3d::vec3 &dir)
Convex-hull support: vertex of h farthest along dir.
AABB rbc::compute_aabb (const ConvexHull &h, const m3d::tf &tf)
Conservative world AABB from the precomputed local AABB.
constexpr bool rbc::is_gjk_convex (const ConvexHull *)
Tag-dispatched marker: ConvexHull rides the GJK fast path (true).
m3d::scalar rbc::representative_radius (const ConvexHull &h)
Representative size = max |v| over the local vertices.
int rbc::face_corners (const ConvexHull &h, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
Face polygon most aligned with dir.
m3d::scalar rbc::compute_volume (const ConvexHull &h)
Volume of the hull.
m3d::smat3 rbc::compute_inertia_tensor (const ConvexHull &h)
Inertia tensor of a uniform-density hull about its centre of mass.
m3d::vec3 rbc::support (const Cylinder &c, const m3d::vec3 &dir)
Local-space support function for a cylinder.
m3d::scalar rbc::compute_volume (const Cylinder &c)
Volume π · r² · 2h.
m3d::smat3 rbc::compute_inertia_tensor (const Cylinder &c)
Inertia tensor of a uniform-density cylinder about its centre.
AABB rbc::compute_aabb (const Cylinder &c, const m3d::tf &tf)
Tight world AABB via 6-direction support sweep.
constexpr bool rbc::is_gjk_convex (const Cylinder *)
Tag-dispatched marker: cylinder is a convex bounded shape.
m3d::scalar rbc::representative_radius (const Cylinder &c)
Representative size = max(base_radius, half_height).
int rbc::face_corners (const Cylinder &c, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
Disc-approximation face polygon.
m3d::vec3 rbc::support (const Ellipsoid &e, const m3d::vec3 &dir)
Local-space support via Lagrange multipliers.
m3d::scalar rbc::compute_volume (const Ellipsoid &e)
Volume (4/3)·π·a·b·c.
m3d::smat3 rbc::compute_inertia_tensor (const Ellipsoid &e)
Inertia tensor of a uniform-density ellipsoid about its centre.
AABB rbc::compute_aabb (const Ellipsoid &e, const m3d::tf &tf)
Tight world AABB.
constexpr bool rbc::is_gjk_convex (const Ellipsoid *)
Tag-dispatched marker: Ellipsoid is a convex bounded shape (true).
m3d::scalar rbc::representative_radius (const Ellipsoid &e)
Representative size = the largest semi-axis.
int rbc::face_corners (const Ellipsoid &e, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
Disc-approximation face polygon (ellipsoid has no flat face).
int rbc::get_generic_face_corners (const m3d::vec3 &support_pt, const m3d::vec3 &normal, m3d::scalar radius, m3d::vec3 *corners, int capacity)
Build a 4-corner polygon approximating the contact face at support_pt.
HeightmapData * rbc::heightmap_data_create (const float *heights, uint32_t rows, uint32_t cols, const m3d::vec3 &scale, const m3d::vec3 &origin)
Allocate a HeightmapData on the heap and precompute min/max height.
void rbc::heightmap_data_destroy (HeightmapData *hd)
Free a HeightmapData returned by heightmap_data_create.
m3d::vec3 rbc::heightmap_vertex (const HeightmapData &hd, uint32_t row, uint32_t col)
World-space position of the grid vertex at (row, col).
m3d::vec3 rbc::support (const Heightmap &, const m3d::vec3 &)
Stub support function — heightmap is not used through GJK.
AABB rbc::compute_aabb (const Heightmap &h, const m3d::tf &)
World AABB built from precomputed min_height / max_height.
constexpr bool rbc::is_gjk_convex (const Heightmap *)
Tag-dispatched marker: Heightmap is non-convex (false).
m3d::scalar rbc::representative_radius (const Heightmap &)
Returns 0 — terrain has no representative size.
int rbc::face_corners (const Heightmap &, const m3d::tf &, const m3d::vec3 &, m3d::vec3 *, int)
Stub — heightmap pairs go through analytic algorithms.
MeshData * rbc::mesh_data_create (const m3d::vec3 *vertices, uint32_t vert_count, const uint32_t *indices, uint32_t face_count)
Allocate a MeshData and precompute face normals + local AABB.
void rbc::mesh_data_destroy (MeshData *md)
Free a MeshData returned by mesh_data_create.
m3d::vec3 rbc::support (const Mesh &m, const m3d::vec3 &dir)
Convex-hull support: vertex of m farthest along dir.
AABB rbc::compute_aabb (const Mesh &m, const m3d::tf &tf)
Conservative world AABB from the precomputed local AABB.
constexpr bool rbc::is_gjk_convex (const Mesh *)
Tag-dispatched marker: Mesh is treated as non-convex (false).
m3d::scalar rbc::representative_radius (const Mesh &)
Returns 0 — mesh has no single representative size.
int rbc::face_corners (const Mesh &, const m3d::tf &, const m3d::vec3 &, m3d::vec3 *, int)
Stub — mesh pairs go through analytic algorithms.
m3d::vec3 rbc::plane_world_normal (const Plane &p, const m3d::tf &tf)
World-space plane normal: tf.rot * p.normal.
m3d::scalar rbc::plane_world_d (const Plane &p, const m3d::tf &tf)
World-space plane offset: p.d + dot(world_normal, tf.pos).
m3d::vec3 rbc::support (const Plane &, const m3d::vec3 &)
Stub support function — returns zero.
AABB rbc::compute_aabb (const Plane &, const m3d::tf &)
AABB is infinite in all directions.
constexpr bool rbc::is_gjk_convex (const Plane *)
Tag-dispatched marker: Plane is non-convex / unbounded (false).
m3d::scalar rbc::representative_radius (const Plane &)
Returns 0 — unbounded shape has no representative size.
int rbc::face_corners (const Plane &, const m3d::tf &, const m3d::vec3 &, m3d::vec3 *, int)
Stub — Plane pairs go through analytic algorithms.
AABB rbc::compute_aabb (const Shape &shape, const m3d::tf &tf)
World-space AABB of shape placed at tf.
m3d::vec3 rbc::shape_support (const Shape &shape, const m3d::vec3 &dir)
Local-space support point of shape along dir.
int rbc::shape_face_corners (const Shape &shape, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
World-space corners of the face of shape that is most aligned with dir.
m3d::scalar rbc::shape_representative_radius (const Shape &shape)
A representative size used for contact-tolerance scaling.
m3d::vec3 rbc::support (const Sphere &s, const m3d::vec3 &direction)
Local-space support: radius * normalize(direction).
m3d::scalar rbc::compute_volume (const Sphere &s)
Sphere volume (4/3)·π·r³.
m3d::smat3 rbc::compute_inertia_tensor (const Sphere &s)
Inertia tensor of a uniform-density sphere about its centre.
AABB rbc::compute_aabb (const Sphere &s, const m3d::tf &tf)
World AABB: [tf.pos - r, tf.pos + r].
constexpr bool rbc::is_gjk_convex (const Sphere *)
Tag-dispatched marker: Sphere is a convex bounded shape (true).
m3d::scalar rbc::representative_radius (const Sphere &s)
Representative size = the radius.
int rbc::face_corners (const Sphere &s, const m3d::tf &tf, const m3d::vec3 &dir, m3d::vec3 *out, int capacity)
Disc-approximation face polygon at the support point along dir.
Variables
template<class T >
constexpr bool rbc::gjk_convex_v
Compile-time predicate: true iff T is a convex bounded shape.
constexpr int rbc::kMaxFaceCorners = 16
Maximum corners any single shape's face_corners may write.
Detailed Description
Collision shapes, broad-phase, narrow-phase, GJK/EPA, and contact manifolds.
The rbc library answers a single question: given two shapes with poses, are they overlapping, and if so, where? It is split into three layers:
Shapes (include/rbc/shapes/) — geometric primitives plus a uniform interface (support, compute_aabb, face_corners, is_gjk_convex, representative_radius). All shape kinds are discriminated through a std::variant in Shape.
Broad / narrow phase (AABB.hpp, BroadPhase.hpp, narrow_phase.hpp, Dispatcher.hpp) — bounding-box pruning, then per-pair dispatch to the right algorithm.
Algorithms (gjk/, analytic/) — GJK + EPA for generic convex pairs, hand-written analytic routines for common pairs where they beat GJK on speed and robustness.
All public collision queries return a ContactManifold (defined in gjk/ContactManifoldGenerator.hpp) with up to 4 contact points.
Typedef Documentation
BPHandle
using rbc::BPHandle = typedef uint32_t
Opaque handle for a registered broad-phase object.
Returned by broad_phase_insert; passed to broad_phase_move / broad_phase_remove. Handles are not stable IDs — they refer to a slot inside BroadPhaseState::objects and are recycled after broad_phase_remove.
Definition at line 51 of file BroadPhase.hpp.
Function Documentation
aabb_expand()
AABB rbc::aabb_expand (const AABB & a, m3d::scalar margin) inline
Expand the AABB by a uniform margin on all sides.
Used to "fatten" AABBs for broad-phase temporal coherence: a moving object only triggers a re-sort when its tight AABB escapes its fattened wrapper.
Definition at line 85 of file AABB.hpp.
References rbc::AABB::max, and rbc::AABB::min.
aabb_surface_area()
m3d::scalar rbc::aabb_surface_area (const AABB & a) inline
Surface area of the AABB.
Used by SAH-style cost heuristics — handy if the broad phase ever switches from sweep-and-prune to a BVH.
Definition at line 111 of file AABB.hpp.
References rbc::AABB::max, and rbc::AABB::min.
broad_phase_insert()
BPHandle rbc::broad_phase_insert (BroadPhaseState & bp, uint32_t user_id, const AABB & tight_aabb)
Register a new object.
Parameters
bp Broad-phase state.
user_id Opaque ID the caller will use to recognise this object in the BroadPhasePair output.
tight_aabb The object's current (un-fattened) AABB.
Returns
Handle used for future broad_phase_move / broad_phase_remove calls.
Referenced by rbps::create_collider().
broad_phase_remove()
void rbc::broad_phase_remove (BroadPhaseState & bp, BPHandle h)
Unregister an object.
The handle is invalidated; its slot is recycled.
Referenced by rbps::collider_remove().
broad_phase_move()
void rbc::broad_phase_move (BroadPhaseState & bp, BPHandle h, const AABB & new_tight_aabb)
Notify the broad phase that an object has moved.
Internally checks whether the new tight AABB is still contained in the previously-fattened AABB. Only triggers a re-insert (and a re-sort on the next update) if the tight AABB escaped.
Referenced by broad_phase_move_shape(), and broad_phase_move_swept().
broad_phase_update()
void rbc::broad_phase_update (BroadPhaseState & bp)
Run the broad phase.
Refills bp.pairs with all potential contact pairs.
Call once per frame after every broad_phase_move for that frame.
Referenced by rbps::World::step().
broad_phase_move_swept()
void rbc::broad_phase_move_swept (BroadPhaseState & bp, BPHandle h, const AABB & tight_aabb, const m3d::vec3 & linear_velocity, m3d::scalar dt) inline
Velocity-expanded move (anti-tunnelling).
Expands the AABB asymmetrically per axis based on linear velocity and the physics timestep so the stored fat AABB covers the entire volume the object will sweep through before the next broad_phase_update call.
Per-axis rule
vel > 0 → max side expands by vel*dt, min side by fat_margin
vel < 0 → min side expands by |vel|*dt, max side by fat_margin
vel == 0 → both sides expand by fat_margin (same as standard move)
Temporal coherence is preserved: broad_phase_move is still called internally, so re-sorts are skipped if the swept AABB fits inside the previously stored fat_aabb.
Definition at line 228 of file BroadPhase.hpp.
References broad_phase_move(), rbc::BroadPhaseState::config, rbc::BroadPhaseConfig::fat_margin, rbc::AABB::max, and rbc::AABB::min.
Referenced by broad_phase_move_shape_swept().
test_narrow_phase()
bool rbc::test_narrow_phase (const Shape & shape_a, const m3d::tf & tf_a, const Shape & shape_b, const m3d::tf & tf_b, rbc::ContactManifold & manifold)
Test a single shape pair and fill a ContactManifold on overlap.
Routes through the dispatch table in Dispatcher.hpp: analytic algorithms for the supported pairs, GJK + EPA + manifold generation otherwise. Non-convex pairs without an analytic specialisation return false.
Parameters
shape_a First collider.
tf_a Transform for shape_a.
shape_b Second collider.
tf_b Transform for shape_b.
[out] manifold Filled with up to 4 contact points; normal points from A toward B.
Returns
true if the shapes overlap and manifold is populated.
compute_inertia_tensor() [1/7]
m3d::smat3 rbc::compute_inertia_tensor (const Box & box) inline
Inertia tensor of a uniform-density box about its centre.
Diagonal entries follow the standard (1/12)·m·(side_a² + side_b²) formula; off-diagonals are zero. Mass is taken as the volume (unit density).
Definition at line 72 of file Box.hpp.
References compute_volume(), and rbc::Box::half_extents.
compute_aabb() [1/7]
AABB rbc::compute_aabb (const Box & b, const m3d::tf & tf) inline
Tight world AABB of an oriented box.
Computed by projecting the OBB onto each world axis: the world-space half-extent along axis i is Σ_j |R_ij| · h_j. Standard derivation for a rotated box; cheaper than evaluating all 8 corners.
Note
Assumes m3d::mat3_cast(quat) returns a column-major mat3 where mat[col][row] indexes the element. Adjust the indexing if your math3d uses a different convention.
Definition at line 101 of file Box.hpp.
References m3d::abs(), rbc::Box::half_extents, m3d::mat3_cast(), m3d::tf::pos, and m3d::tf::rot.
Referenced by broad_phase_move_shape(), broad_phase_move_shape_swept(), compute_aabb(), and rbps::create_collider().
face_corners() [1/3]
int rbc::face_corners (const Box & b, const m3d::tf & tf, const m3d::vec3 & dir, m3d::vec3 * corners, int capacity) inline
4 corners of the box face whose outward normal is most aligned with dir.
This is the only shape that returns an exact face polygon (rather than the disc approximation in FaceHelpers). The contact manifold generator uses it as the reference / incident polygon for box pairs, which is what gives box–box contacts their stable 4-point manifold.
Returns
Always 4.
Definition at line 135 of file Box.hpp.
References m3d::abs(), m3d::dot(), rbc::Box::half_extents, m3d::tf::pos, and m3d::tf::rotate_vector().
Referenced by shape_face_corners().
capsule_endpoints()
void rbc::capsule_endpoints (const Capsule & c, const m3d::tf & tf, m3d::vec3 & p1_out, m3d::vec3 & p2_out) inline
World-space endpoints of the capsule's central segment.
Parameters
c Capsule shape.
tf Body transform.
[out] p1_out Endpoint on the +Y side of local space.
[out] p2_out Endpoint on the −Y side of local space.
Definition at line 55 of file Capsule.hpp.
References rbc::Capsule::half_height, m3d::tf::pos, and m3d::tf::rotate_vector().
Referenced by rbc::CollisionAlgorithm< Capsule, Capsule >::test(), rbc::CollisionAlgorithm< Capsule, Box >::test(), and rbc::CollisionAlgorithm< Sphere, Capsule >::test().
support() [1/8]
m3d::vec3 rbc::support (const Capsule & c, const m3d::vec3 & dir) inline
Local-space support: pick the cap centre on the side dir.y points to, then nudge by radius * normalize(dir).
The Minkowski-sum identity: capsule = segment ⊕ sphere, so support_capsule = support_segment + support_sphere.
Definition at line 72 of file Capsule.hpp.
References m3d::EPSILON, rbc::Capsule::half_height, m3d::length(), and rbc::Capsule::radius.
compute_inertia_tensor() [2/7]
m3d::smat3 rbc::compute_inertia_tensor (const Capsule & c) inline
Inertia tensor of a uniform-density capsule about its centre.
Built from the cylinder + two hemispheres composition; the hemisphere contribution to the transverse axis uses the parallel-axis theorem with offset h + 3r/8. Reference: Eberly, Game Physics, capsule moment integrals.
Definition at line 99 of file Capsule.hpp.
References compute_volume(), rbc::Capsule::half_height, m3d::PI, and rbc::Capsule::radius.
compute_aabb() [2/7]
AABB rbc::compute_aabb (const Capsule & c, const m3d::tf & tf) inline
Tight world AABB.
Computed as the union of two radius-sized boxes around the world endpoints — exact for a capsule and cheaper than a 6-direction support sweep.
Definition at line 129 of file Capsule.hpp.
References rbc::Capsule::half_height, m3d::max(), m3d::min(), m3d::tf::pos, rbc::Capsule::radius, and m3d::tf::rotate_vector().
support() [2/8]
m3d::vec3 rbc::support (const Cone & c, const m3d::vec3 & dir) inline
Local-space support — pick the apex or a point on the base circle.
Two candidates compete: the apex (0, h, 0) and the base-edge point in the radial direction of dir. The winner is whichever has the larger inner product with dir. Closed-form, no iteration.
Definition at line 52 of file Cone.hpp.
References rbc::Cone::base_radius, m3d::EPSILON, rbc::Cone::half_height, and m3d::sqrt().
compute_inertia_tensor() [3/7]
m3d::smat3 rbc::compute_inertia_tensor (const Cone & c) inline
Inertia tensor of a uniform-density cone about its centre.
The transverse moment is computed about the apex and shifted to the centroid (which sits at 3H/8 from the base, i.e. h/4 from the local origin) using the parallel-axis theorem.
Iyy (axial) = (3/10) · m · R²
Ixx (transverse) derived as above.
Definition at line 92 of file Cone.hpp.
References rbc::Cone::base_radius, compute_volume(), and rbc::Cone::half_height.
compute_aabb() [3/7]
AABB rbc::compute_aabb (const Cone & c, const m3d::tf & tf) inline
Tight world AABB via 6-direction support sweep.
More accurate than a bounding sphere, still O(1).
Definition at line 111 of file Cone.hpp.
References m3d::tf::inverse_rotate_vector(), m3d::max(), m3d::min(), m3d::tf::pos, m3d::tf::rotate_vector(), and support().
convex_hull_data_create()
ConvexHullData * rbc::convex_hull_data_create (const m3d::vec3 * vertices, uint32_t vert_count, const uint32_t * face_indices = nullptr, uint32_t face_count = 0) inline
Allocate a ConvexHullData and precompute face normals + local AABB.
The caller-supplied vertices and face_indices arrays are referenced, not copied — they must outlive the returned ConvexHullData. The face_normals buffer is allocated and populated by this function; release it with convex_hull_data_destroy.
Pass face_indices == nullptr and face_count == 0 for a vertex-only hull; in that case no normals are allocated and face_normals is left null.
Warning
Assumes counter-clockwise triangle winding (outward normals). The caller is responsible for ensuring the input vertices form a convex polytope; there is no validation at this layer.
Parameters
vertices Local-space vertex positions (referenced, not copied).
vert_count Number of entries in vertices.
face_indices Triangle indices, 3 per face (CCW); may be nullptr.
face_count Number of triangles; pass 0 when face_indices == nullptr.
Returns
Heap-allocated ConvexHullData owned by the caller.
Definition at line 149 of file ConvexHull.hpp.
References m3d::cross(), m3d::dot(), m3d::EPSILON, m3d::length(), m3d::max(), m3d::min(), m3d::normalize(), and rbc::ConvexHullData::vertices.
convex_hull_data_destroy()
void rbc::convex_hull_data_destroy (ConvexHullData * hd) inline
Free a ConvexHullData returned by convex_hull_data_create.
Releases the precomputed face_normals array (when present) and the ConvexHullData itself. The caller-supplied vertices and face_indices arrays are NOT freed — they remain owned by the caller.
Definition at line 432 of file ConvexHull.hpp.
References rbc::ConvexHullData::face_normals, rbc::ConvexHullData::poly_indices, rbc::ConvexHullData::poly_normals, rbc::ConvexHullData::poly_offsets, rbc::ConvexHullData::poly_to_polys_indices, rbc::ConvexHullData::poly_to_polys_offsets, rbc::ConvexHullData::vertex_to_neighbors_indices, rbc::ConvexHullData::vertex_to_neighbors_offsets, rbc::ConvexHullData::vertex_to_polys_indices, and rbc::ConvexHullData::vertex_to_polys_offsets.
support() [3/8]
m3d::vec3 rbc::support (const ConvexHull & h, const m3d::vec3 & dir) inline
Convex-hull support: vertex of h farthest along dir.
Vertex scan over the precomputed local vertex array. Linear in the vertex count, which is fine for typical hulls (≤ 32 vertices).
Definition at line 457 of file ConvexHull.hpp.
References rbc::ConvexHull::data, m3d::dot(), rbc::ConvexHullData::vert_count, and rbc::ConvexHullData::vertices.
compute_aabb() [4/7]
AABB rbc::compute_aabb (const ConvexHull & h, const m3d::tf & tf) inline
Conservative world AABB from the precomputed local AABB.
Same OBB-projection technique as Box::compute_aabb and Mesh::compute_aabb. Conservative — for tight bounds you would project every world vertex, which is no longer O(1).
Definition at line 484 of file ConvexHull.hpp.
References m3d::abs(), rbc::ConvexHull::data, rbc::ConvexHullData::local_aabb, m3d::mat3_cast(), rbc::AABB::max, rbc::AABB::min, m3d::tf::pos, m3d::tf::rot, and m3d::tf::rotate_vector().
is_gjk_convex() [1/3]
constexpr bool rbc::is_gjk_convex (const ConvexHull *) constexpr
Tag-dispatched marker: ConvexHull rides the GJK fast path (true).
Flipping this from false (as Mesh carries it) to true is the single change that promotes a vertex array from "treated as a triangle soup" to "first-class convex collider." The pointer is never dereferenced; this is a compile-time predicate.
Definition at line 511 of file ConvexHull.hpp.
representative_radius()
m3d::scalar rbc::representative_radius (const ConvexHull & h) inline
Representative size = max |v| over the local vertices.
Linear scan; cheap relative to a collision step but consider caching in ConvexHullData if profiling shows it matters.
Definition at line 521 of file ConvexHull.hpp.
References rbc::ConvexHull::data, m3d::length_sq(), m3d::sqrt(), rbc::ConvexHullData::vert_count, and rbc::ConvexHullData::vertices.
face_corners() [2/3]
int rbc::face_corners (const ConvexHull & h, const m3d::tf & tf, const m3d::vec3 & dir, m3d::vec3 * out, int capacity) inline
Face polygon most aligned with dir.
With merged polygons: pick the polygon whose averaged outward normal is most aligned with dir (transformed to local space), transform its vertices to world space, return up to capacity corners. This is the path that supplies the contact-manifold generator with a true logical-face polygon (e.g. the full hexagon of a hex-prism cap rather than one of its 4 fan triangles).
With only triangle data and no merged polygons (vert-only hull or merge produced nothing): fall back to picking the single best-aligned triangle, returning 3 corners.
Without any face data: disc-approximation patch (same as Sphere/Capsule), centred on the world support point.
Parameters
capacity Capacity of out; the returned count is clamped to this. Pass kMaxFaceCorners-sized buffers in manifold-generation callers.
Definition at line 556 of file ConvexHull.hpp.
References rbc::ConvexHull::data, m3d::dot(), rbc::ConvexHullData::face_count, rbc::ConvexHullData::face_indices, rbc::ConvexHullData::face_normals, get_generic_face_corners(), m3d::tf::inverse_rotate_vector(), rbc::ConvexHullData::poly_count, rbc::ConvexHullData::poly_indices, rbc::ConvexHullData::poly_normals, rbc::ConvexHullData::poly_offsets, representative_radius(), support(), m3d::tf::transform_point(), rbc::ConvexHullData::vert_count, and rbc::ConvexHullData::vertices.
compute_volume()
m3d::scalar rbc::compute_volume (const ConvexHull & h) inline
Volume of the hull.
With face data: sum of signed tetrahedron volumes (O, A, B, C) over all triangles, with origin as the apex. Exact for any closed CCW-wound triangulation.
Without face data: volume of the local AABB (loose upper bound).
Definition at line 619 of file ConvexHull.hpp.
References m3d::cross(), rbc::ConvexHull::data, m3d::dot(), rbc::ConvexHullData::face_count, rbc::ConvexHullData::face_indices, rbc::ConvexHullData::local_aabb, rbc::AABB::max, rbc::AABB::min, and rbc::ConvexHullData::vertices.
compute_inertia_tensor() [4/7]
m3d::smat3 rbc::compute_inertia_tensor (const ConvexHull & h) inline
Inertia tensor of a uniform-density hull about its centre of mass.
With face data: tetrahedral decomposition from the origin following the standard polynomial moment integrals (see Mirtich 1996), then translated to the centroid via the parallel-axis theorem. Mass is taken as the volume (unit density) — multiply by your body's density at construction.
Without face data: inertia of the local AABB (Box formula). A one-shot debug message is emitted to stderr so the caller knows the result is approximate. The fallback is silenced under NDEBUG.
Definition at line 656 of file ConvexHull.hpp.
References m3d::abs(), m3d::cross(), rbc::ConvexHull::data, m3d::dot(), m3d::EPSILON, rbc::ConvexHullData::face_count, rbc::ConvexHullData::face_indices, rbc::ConvexHullData::local_aabb, rbc::AABB::max, rbc::AABB::min, and rbc::ConvexHullData::vertices.
support() [4/8]
m3d::vec3 rbc::support (const Cylinder & c, const m3d::vec3 & dir) inline
Local-space support function for a cylinder.
A cylinder's support decomposes cleanly into two independent parts:
Y axis: the support is always ±half_height depending on sign(dir.y).
XZ plane: the support is the point on the rim in the direction of the XZ projection of dir, scaled to base_radius.
When the XZ projection of dir is degenerate (purely axial direction), any point on the rim is equally valid — we pick (base_radius, ±h, 0).
Definition at line 57 of file Cylinder.hpp.
References rbc::Cylinder::base_radius, m3d::EPSILON, rbc::Cylinder::half_height, and m3d::sqrt().
compute_inertia_tensor() [5/7]
m3d::smat3 rbc::compute_inertia_tensor (const Cylinder & c) inline
Inertia tensor of a uniform-density cylinder about its centre.
Iyy (axial) = (1/2) · m · R²
Ixx = Izz (transverse) = (1/12) · m · (3R² + H_total²)
Definition at line 89 of file Cylinder.hpp.
References rbc::Cylinder::base_radius, compute_volume(), and rbc::Cylinder::half_height.
support() [5/8]
m3d::vec3 rbc::support (const Ellipsoid & e, const m3d::vec3 & dir) inline
Local-space support via Lagrange multipliers.
For the constraint (x/a)² + (y/b)² + (z/c)² ≤ 1, the support point along dir is: p_k = a_k² · d_k / sqrt(Σ a_k² · d_k²).
Definition at line 46 of file Ellipsoid.hpp.
References m3d::EPSILON, rbc::Ellipsoid::half_extents, and m3d::sqrt().
compute_inertia_tensor() [6/7]
m3d::smat3 rbc::compute_inertia_tensor (const Ellipsoid & e) inline
Inertia tensor of a uniform-density ellipsoid about its centre.
Diagonal entries Iii = (2/5)·m·(j² + k²) cycled over the three axes. Mass is taken as the volume (unit density).
Definition at line 74 of file Ellipsoid.hpp.
References compute_volume(), and rbc::Ellipsoid::half_extents.
compute_aabb() [5/7]
AABB rbc::compute_aabb (const Ellipsoid & e, const m3d::tf & tf) inline
Tight world AABB.
World-space half-extent along axis i is sqrt(R[0][i]²·a² + R[1][i]²·b² + R[2][i]²·c²). Same derivation as Box::compute_aabb but with sum-of-squares instead of sum-of-|·|.
Definition at line 96 of file Ellipsoid.hpp.
References rbc::Ellipsoid::half_extents, m3d::mat3_cast(), m3d::tf::pos, m3d::tf::rot, and m3d::sqrt().
get_generic_face_corners()
int rbc::get_generic_face_corners (const m3d::vec3 & support_pt, const m3d::vec3 & normal, m3d::scalar radius, m3d::vec3 * corners, int capacity) inline
Build a 4-corner polygon approximating the contact face at support_pt.
Used as the face_corners fallback for convex shapes that don't have a flat face on the contact normal (Sphere, Capsule, Ellipsoid, Cone). The polygon is a square of side radius lying in the plane normal to normal and centred on support_pt.
Lives in this small header to break a cycle: every shape's face_corners needs this helper, but ContactManifoldGenerator.hpp (which is the natural home) depends on every shape.
Parameters
support_pt World-space point that the polygon is centred on.
normal Unit world-space contact normal.
radius Patch half-size (typically representative_radius).
[out] corners Buffer with capacity ≥ 4.
capacity Capacity of corners; the call writes 0 if < 4.
Returns
Number of corners written (0 or 4).
Definition at line 45 of file FaceHelpers.hpp.
References m3d::abs(), m3d::cross(), and m3d::normalize().
Referenced by face_corners(), face_corners(), face_corners(), face_corners(), face_corners(), and face_corners().
heightmap_data_create()
HeightmapData * rbc::heightmap_data_create (const float * heights, uint32_t rows, uint32_t cols, const m3d::vec3 & scale, const m3d::vec3 & origin) inline
Allocate a HeightmapData on the heap and precompute min/max height.
Caller owns the returned pointer and must call heightmap_data_destroy to free it. The heights array is referenced, not copied — keep it alive for as long as the returned HeightmapData is in use.
Definition at line 82 of file Heightmap.hpp.
References rbc::HeightmapData::heights.
support() [6/8]
m3d::vec3 rbc::support (const Heightmap & , const m3d::vec3 &) inline
Stub support function — heightmap is not used through GJK.
Heightmap pairs go through analytic algorithms in analytic/HeightmapCollision.hpp.
Definition at line 131 of file Heightmap.hpp.
mesh_data_create()
MeshData * rbc::mesh_data_create (const m3d::vec3 * vertices, uint32_t vert_count, const uint32_t * indices, uint32_t face_count) inline
Allocate a MeshData and precompute face normals + local AABB.
Assumes counter-clockwise triangle winding (outward normals). Caller owns the returned pointer; call mesh_data_destroy to free it. The vertices and indices arrays are referenced, not copied.
Definition at line 68 of file Mesh.hpp.
References m3d::cross(), m3d::max(), m3d::min(), m3d::normalize(), and rbc::MeshData::vertices.
mesh_data_destroy()
void rbc::mesh_data_destroy (MeshData * md) inline
Free a MeshData returned by mesh_data_create.
Also frees the precomputed face-normals array.
Definition at line 111 of file Mesh.hpp.
References rbc::MeshData::face_normals.
support() [7/8]
m3d::vec3 rbc::support (const Mesh & m, const m3d::vec3 & dir) inline
Convex-hull support: vertex of m farthest along dir.
Warning
Only valid for convex meshes. Concave meshes must go through the per-triangle analytic path in analytic/MeshCollision.hpp.
Definition at line 126 of file Mesh.hpp.
References rbc::Mesh::data, m3d::dot(), rbc::MeshData::vert_count, and rbc::MeshData::vertices.
compute_aabb() [6/7]
AABB rbc::compute_aabb (const Mesh & m, const m3d::tf & tf) inline
Conservative world AABB from the precomputed local AABB.
Same OBB-projection technique as Box::compute_aabb. The result is a conservative wrapper — for tighter bounds you'd need to project every world vertex, which is no longer O(1).
Definition at line 153 of file Mesh.hpp.
References m3d::abs(), rbc::Mesh::data, rbc::MeshData::local_aabb, m3d::mat3_cast(), rbc::AABB::max, rbc::AABB::min, m3d::tf::pos, m3d::tf::rot, and m3d::tf::rotate_vector().
is_gjk_convex() [2/3]
constexpr bool rbc::is_gjk_convex (const Mesh *) constexpr
Tag-dispatched marker: Mesh is treated as non-convex (false).
Convex meshes work too, but the supported path is the analytic specialisation in analytic/MeshCollision.hpp.
Definition at line 178 of file Mesh.hpp.
support() [8/8]
m3d::vec3 rbc::support (const Plane & , const m3d::vec3 &) inline
Stub support function — returns zero.
Plane is non-convex (infinite). is_gjk_convex(const Plane*) == false, so the dispatcher's compile-time guard prevents GJK from ever calling this. The overload exists only so the variant-level shape_support dispatch compiles.
Definition at line 70 of file Plane.hpp.
compute_aabb() [7/7]
AABB rbc::compute_aabb (const Shape & shape, const m3d::tf & tf) inline
World-space AABB of shape placed at tf.
Variant-level dispatcher: routes through std::visit to the per-shape compute_aabb(const T&, const tf&) overload.
Definition at line 116 of file ShapeTypes.hpp.
References compute_aabb().
shape_support()
m3d::vec3 rbc::shape_support (const Shape & shape, const m3d::vec3 & dir) inline
Local-space support point of shape along dir.
Variant-level dispatcher used by GJK. Only meaningful for convex shapes (is_gjk_convex(const T*) == true); non-convex shapes return a placeholder and should never be called this way at runtime.
Definition at line 130 of file ShapeTypes.hpp.
References support().
Referenced by rbc::MinkowskiDiff::support_a(), and rbc::MinkowskiDiff::support_b().
shape_face_corners()
int rbc::shape_face_corners (const Shape & shape, const m3d::tf & tf, const m3d::vec3 & dir, m3d::vec3 * out, int capacity) inline
World-space corners of the face of shape that is most aligned with dir.
Used by the contact-manifold generator as the reference / incident polygon. Returns the number of corners written (up to capacity); shapes without flat faces fall back to a disc approximation in get_generic_face_corners. ConvexHull may return up to its largest merged-polygon size — pass at least kMaxFaceCorners.
Definition at line 146 of file ShapeTypes.hpp.
References face_corners().
shape_representative_radius()
m3d::scalar rbc::shape_representative_radius (const Shape & shape) inline
A representative size used for contact-tolerance scaling.
Roughly the largest principal radius / half-extent of the shape. Returns 0 for unbounded shapes (Plane, Heightmap, Mesh).
Definition at line 160 of file ShapeTypes.hpp.
References representative_radius().
compute_inertia_tensor() [7/7]
m3d::smat3 rbc::compute_inertia_tensor (const Sphere & s) inline
Inertia tensor of a uniform-density sphere about its centre.
Ixx = Iyy = Izz = (2/5)·m·r², off-diagonals zero. Mass is taken as the volume (unit density) — multiply the result by your body's density at construction time.
Definition at line 68 of file Sphere.hpp.
References compute_volume(), and rbc::Sphere::radius.
is_gjk_convex() [3/3]
constexpr bool rbc::is_gjk_convex (const Sphere *) constexpr
Tag-dispatched marker: Sphere is a convex bounded shape (true).
The pointer is never dereferenced; this is a compile-time predicate.
Definition at line 96 of file Sphere.hpp.
face_corners() [3/3]
int rbc::face_corners (const Sphere & s, const m3d::tf & tf, const m3d::vec3 & dir, m3d::vec3 * out, int capacity) inline
Disc-approximation face polygon at the support point along dir.
Spheres have no flat face; this routes through get_generic_face_corners so the contact manifold generator gets a usable 4-corner patch.
Definition at line 109 of file Sphere.hpp.
References get_generic_face_corners(), m3d::tf::inverse_rotate_vector(), representative_radius(), support(), and m3d::tf::transform_point().
Variable Documentation
gjk_convex_v
template<class T > constexpr bool rbc::gjk_convex_v inline constexpr
Initial value:
=
        is_gjk_convex(static_cast<const T *>(nullptr))
Compile-time predicate: true iff T is a convex bounded shape.
Forwards to the per-shape free function is_gjk_convex(const T*). The pointer tag avoids requiring a default constructor on every shape; the value is never read.
Definition at line 54 of file Dispatcher.hpp.
kMaxFaceCorners
constexpr int rbc::kMaxFaceCorners = 16 constexpr
Maximum corners any single shape's face_corners may write.
Caller-supplied buffers passed to face_corners / shape_face_corners are sized to this. Set high enough for the largest convex-hull polygon the engine expects to see (12 = a regular dodecagon cap, with room to spare). Increase if you build hulls with > 16-vertex faces.
Definition at line 22 of file FaceHelpers.hpp.