RBPS: m3d::mat3 Struct Reference
m3d::mat3 Struct Reference
math3d — 3D math primitives
Dense 3×3 matrix in column-major layout.
#include <mat3.hpp>
Public Member Functions
mat3 ()
Identity matrix.
mat3 (scalar m00, scalar m01, scalar m02, scalar m10, scalar m11, scalar m12, scalar m20, scalar m21, scalar m22)
Element-wise constructor in row-major reading order.
vec3 & operator[] (int i)
Indexed mutable column access.
const vec3 & operator[] (int i) const
Indexed const column access.
vec3 operator* (const vec3 &v) const
Matrix–vector product (M * v).
mat3 operator* (const mat3 &rhs) const
Matrix–matrix product ((*this) * rhs).
bool operator== (const mat3 &other) const
Bitwise-exact equality.
bool is_approx (const mat3 &other, scalar precision=EPSILON) const
Tolerance-based equality (per-element).
mat3 transpose () const
Transpose.
scalar determinant () const
3×3 determinant.
mat3 inverse () const
Inverse via classical adjugate.
Public Attributes
vec3 cols [3]
Column-major storage; cols[i] is the i-th column.
Friends
std::ostream & operator<< (std::ostream &os, const mat3 &m)
Pretty-printed stream insertion (3 rows in | a b c | form).
Detailed Description
Dense 3×3 matrix in column-major layout.
Used for general linear transforms: rotation matrices, basis changes, and as the dense form of the inertia tensor when needed by code that doesn't exploit symmetry.
The element-wise constructor takes arguments in row-major reading order (m00, m01, m02, m10, ...) but stores them column-major; this matches how matrices are typically written down on paper.
mat3 R = mat3_cast(quat::from_axis_angle({0,1,0}, PI/2));
vec3 r = R * vec3{1, 0, 0};   // rotated point
Definition at line 33 of file mat3.hpp.
Constructor & Destructor Documentation
mat3()
m3d::mat3::mat3 (scalar m00, scalar m01, scalar m02, scalar m10, scalar m11, scalar m12, scalar m20, scalar m21, scalar m22) inline
Element-wise constructor in row-major reading order.
Parameters are named mRC where R is the row and C is the column.
Definition at line 50 of file mat3.hpp.
References cols.
Member Function Documentation
operator==()
bool m3d::mat3::operator== (const mat3 & other) const inline
Bitwise-exact equality.
Use is_approx for tolerance.
Definition at line 85 of file mat3.hpp.
References cols.
is_approx()
bool m3d::mat3::is_approx (const mat3 & other, scalar precision = EPSILON) const inline
Tolerance-based equality (per-element).
Parameters
other Matrix to compare against.
precision Absolute per-element tolerance (default EPSILON).
Definition at line 95 of file mat3.hpp.
References cols.
inverse()
mat3 m3d::mat3::inverse () const inline
Inverse via classical adjugate.
Returns the identity matrix when the determinant is below EPSILON, to keep callers from having to special-case singular inputs.
Definition at line 125 of file mat3.hpp.
References m3d::abs(), cols, determinant(), m3d::EPSILON, and mat3().
The documentation for this struct was generated from the following file:
/home/runner/work/rbps/rbps/include/math3d/mat3.hpp