RBPS: m3d::tf Struct Reference
m3d::tf Struct Reference
math3d — 3D math primitives
Rigid (SE(3)) transform = translation + rotation.
#include <tf.hpp>
Public Member Functions
tf ()
Identity transform (origin, no rotation).
tf (const vec3 &p, const quat &q)
Build from a translation and a (preferably unit) quaternion.
vec3 transform_point (const vec3 &p) const
Map a point from this frame's local space to world space.
vec3 rotate_vector (const vec3 &d) const
Rotate a free vector (direction) — translation is ignored.
vec3 inverse_rotate_vector (const vec3 &d) const
Rotate a world-space direction back into this frame's local space.
Public Attributes
vec3 pos
Translation, applied after rotation.
quat rot
Rotation, applied first.
Detailed Description
Rigid (SE(3)) transform = translation + rotation.
Represents a frame change with no scaling or shear. Used pervasively for body poses, joint frames, sensor mounting, etc. Composition is intentionally not provided as an operator — chain the helpers explicitly to make ordering obvious.
tf body_pose{ {0, 5, 0}, quat::from_axis_angle({0,1,0}, PI/4) };
vec3 corner_local{0.5, 0.5, 0.5};
vec3 corner_world = body_pose.transform_point(corner_local);
Examples
test_dispatcher.cpp.
Definition at line 29 of file tf.hpp.
Member Function Documentation
transform_point()
vec3 m3d::tf::transform_point (const vec3 & p) const inline
Map a point from this frame's local space to world space.
Computes pos + rot * p.
Parameters
p Point in local coordinates.
Returns
Point in world coordinates.
Definition at line 47 of file tf.hpp.
References pos, rot, and m3d::rotate().
Referenced by rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::MinkowskiDiff::support_a(), rbc::MinkowskiDiff::support_b(), and rbc::CollisionAlgorithm< Sphere, Box >::test().
rotate_vector()
vec3 m3d::tf::rotate_vector (const vec3 & d) const inline
Rotate a free vector (direction) — translation is ignored.
Use this for vectors that are not anchored to the origin, such as normals, axes, velocities, and force directions.
Parameters
d Vector in local coordinates.
Returns
Vector in world coordinates.
Definition at line 61 of file tf.hpp.
References rot, and m3d::rotate().
Referenced by rbc::capsule_endpoints(), rbc::compute_aabb(), rbc::compute_aabb(), rbc::compute_aabb(), rbc::compute_aabb(), rbc::compute_aabb(), rbc::face_corners(), rbc::plane_world_normal(), rbc::CollisionAlgorithm< Box, Box >::test(), rbc::CollisionAlgorithm< Capsule, Box >::test(), and rbc::CollisionAlgorithm< Sphere, Box >::test().
inverse_rotate_vector()
vec3 m3d::tf::inverse_rotate_vector (const vec3 & d) const inline
Rotate a world-space direction back into this frame's local space.
Equivalent to rotate(conjugate(rot), d) for unit rot.
Parameters
d Vector in world coordinates.
Returns
Vector in this frame's local coordinates.
Definition at line 74 of file tf.hpp.
References m3d::conjugate(), rot, and m3d::rotate().
Referenced by rbc::compute_aabb(), rbc::compute_aabb(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::face_corners(), rbc::MinkowskiDiff::support_a(), rbc::MinkowskiDiff::support_b(), and rbc::CollisionAlgorithm< Sphere, Box >::test().
The documentation for this struct was generated from the following file:
/home/runner/work/rbps/rbps/include/math3d/tf.hpp