RBPS: SoABase< Derived, IdType, Capacity, GenerationBits > Struct Template Reference
SoABase< Derived, IdType, Capacity, GenerationBits > Struct Template Reference
storage — Structure-of-Arrays containers
CRTP base for fixed-capacity Structure-of-Arrays containers.
#include <Soa.hpp>
Public Member Functions
IdType add ()
Allocate a new item and return its stable ID.
template<typename Fn >
IdType emplace (Fn &&fn)
Allocate a new item and immediately write fields via a callback.
template<typename Fn >
void add_n (IdType n, Fn &&on_added)
Bulk-allocate n items, calling on_added for each.
void remove (IdType id)
Remove an item in O(1) via swap-and-pop.
IdType index_of (IdType id) const
Return the packed data index for a stable ID.
bool contains (IdType id) const
Return true if id refers to a currently live item.
template<typename Fn >
void for_each_index (Fn &&fn)
Iterate over all live items by packed data index.
template<typename Fn >
void for_each_index (Fn &&fn) const
Iterate over all live items by packed data index.
template<typename Fn >
void for_each_id (Fn &&fn)
Iterate over all live items by stable versioned ID.
template<typename Fn >
void for_each_id (Fn &&fn) const
Iterate over all live items by stable versioned ID.
IdType count () const
Return the number of currently live items.
void clear ()
Remove all items.
Static Public Member Functions
static constexpr IdType max_capacity ()
Return the compile-time maximum capacity.
Public Attributes
IdType _data_index [Capacity]
slot → packed data index (or INVALID)
IdType _ids [Capacity]
packed data index → full versioned ID
IdType _free_slots [Capacity]
recycled slot stack
IdType _generation [Capacity]
slot → generation counter
Detailed Description
template<typename Derived, typename IdType, IdType Capacity, uint8_t GenerationBits>
struct SoABase< Derived, IdType, Capacity, GenerationBits >
CRTP base for fixed-capacity Structure-of-Arrays containers.
Provides stable versioned IDs, O(1) add/remove/lookup, and iteration helpers. Concrete structs are generated via DEFINE_SOA; this base is not used directly.
Template Parameters
Derived The generated concrete struct (CRTP pattern).
IdType Unsigned integer type for IDs (e.g. uint32_t).
Capacity Compile-time maximum number of live items.
GenerationBits Bits of IdType reserved for the generation counter. Set to 0 to disable versioning entirely.
Definition at line 62 of file Soa.hpp.
Member Function Documentation
add()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> IdType SoABase< Derived, IdType, Capacity, GenerationBits >::add () inline
Allocate a new item and return its stable ID.
All fields at the new packed slot are zero-initialised (the concrete struct's arrays are value-initialised at construction; add() only advances the bookkeeping, so callers should write fields immediately).
Returns
Stable versioned ID. Store it to reference this item later.
Definition at line 111 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::_data_index, SoABase< Derived, IdType, Capacity, GenerationBits >::_free_slots, SoABase< Derived, IdType, Capacity, GenerationBits >::_generation, and SoABase< Derived, IdType, Capacity, GenerationBits >::_ids.
Referenced by SoABase< Derived, IdType, Capacity, GenerationBits >::add_n(), and SoABase< Derived, IdType, Capacity, GenerationBits >::emplace().
emplace()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> template<typename Fn > IdType SoABase< Derived, IdType, Capacity, GenerationBits >::emplace (Fn && fn) inline
Allocate a new item and immediately write fields via a callback.
Template Parameters
Fn Callable with signature void(IdType id, Derived& self).
Parameters
fn Called right after allocation with the new ID and the collection.
Returns
Stable versioned ID.
Example
bc.emplace([&](uint32_t id, auto& c) {
    uint32_t i    = c.index_of(id);
    c.position[i] = {0, 5, 0};
    c.mass[i]     = 2.0f;
});
Definition at line 145 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::add().
add_n()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> template<typename Fn > void SoABase< Derived, IdType, Capacity, GenerationBits >::add_n (IdType n, Fn && on_added) inline
Bulk-allocate n items, calling on_added for each.
Template Parameters
Fn Callable with signature void(IdType id).
Parameters
n Number of items to allocate.
on_added Called once per new item.
Definition at line 162 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::add().
remove()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> void SoABase< Derived, IdType, Capacity, GenerationBits >::remove (IdType id) inline
Remove an item in O(1) via swap-and-pop.
The last live item slides into the freed slot; data order is NOT preserved. Stale or already-removed IDs are silently ignored.
Parameters
id Stable ID returned by add() or emplace().
Definition at line 178 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::_data_index, SoABase< Derived, IdType, Capacity, GenerationBits >::_free_slots, SoABase< Derived, IdType, Capacity, GenerationBits >::_generation, and SoABase< Derived, IdType, Capacity, GenerationBits >::_ids.
index_of()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> IdType SoABase< Derived, IdType, Capacity, GenerationBits >::index_of (IdType id) const inline
Return the packed data index for a stable ID.
Use this when you need to write or read a single item by ID outside of a full iteration loop.
No bounds-checking is performed. Call contains() first if the ID may be stale.
Parameters
id Stable ID.
Returns
Packed array index in [0, count()).
Example
uint32_t i    = bc.index_of(ball);
bc.position[i] = {1, 2, 3};
Definition at line 232 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::_data_index.
contains()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> bool SoABase< Derived, IdType, Capacity, GenerationBits >::contains (IdType id) const inline
Return true if id refers to a currently live item.
Parameters
id ID to test (may be stale or out-of-range).
Definition at line 241 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::_data_index, and SoABase< Derived, IdType, Capacity, GenerationBits >::_ids.
for_each_index() [1/2]
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> template<typename Fn > void SoABase< Derived, IdType, Capacity, GenerationBits >::for_each_index (Fn && fn) inline
Iterate over all live items by packed data index.
Template Parameters
Fn Callable with signature void(IdType data_index).
Definition at line 262 of file Soa.hpp.
for_each_index() [2/2]
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> template<typename Fn > void SoABase< Derived, IdType, Capacity, GenerationBits >::for_each_index (Fn && fn) const inline
Iterate over all live items by packed data index.
Template Parameters
Fn Callable with signature void(IdType data_index).
Definition at line 270 of file Soa.hpp.
for_each_id() [1/2]
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> template<typename Fn > void SoABase< Derived, IdType, Capacity, GenerationBits >::for_each_id (Fn && fn) inline
Iterate over all live items by stable versioned ID.
Template Parameters
Fn Callable with signature void(IdType id).
Definition at line 282 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::_ids.
for_each_id() [2/2]
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> template<typename Fn > void SoABase< Derived, IdType, Capacity, GenerationBits >::for_each_id (Fn && fn) const inline
Iterate over all live items by stable versioned ID.
Template Parameters
Fn Callable with signature void(IdType id).
Definition at line 290 of file Soa.hpp.
References SoABase< Derived, IdType, Capacity, GenerationBits >::_ids.
clear()
template<typename Derived , typename IdType , IdType Capacity, uint8_t GenerationBits> void SoABase< Derived, IdType, Capacity, GenerationBits >::clear () inline
Remove all items.
Generation counters are preserved so old IDs stay stale.
Definition at line 308 of file Soa.hpp.
The documentation for this struct was generated from the following file:
/home/runner/work/rbps/rbps/include/storage/Soa.hpp