RBPS: rbps::World Struct Reference
rbps::World Struct Reference
rbps — Physics core
Owns the simulation state and runs the per-frame step loop.
#include <World.hpp>
Public Member Functions
World ()=default
Default-construct a world with 60 Hz / 20 substeps.
World (scalar timestep_, int substeps_)
Construct with explicit timestep and substep count.
uint32_t create_body (BodyParams params)
Create a body.
uint32_t create_collider (ColliderParams params)
Create a collider attached to an existing body.
uint32_t create_constraint (ConstraintParams params)
Create a low-level constraint row.
uint32_t create_prismatic_joint (PrismaticJointParams params)
Create a prismatic (sliding) joint.
uint32_t create_revolute_joint (RevoluteJointParams params)
Create a revolute (hinge) joint.
uint32_t create_fixed_joint (FixedJointParams params)
Create a fixed (rigidly-locked) joint.
void solve_positions (scalar inv_h, scalar h)
Position-level solver for one substep.
void solve_velocities (scalar h)
Velocity-level solver for one substep (restitution + friction + joint damping).
void step ()
Advance the simulation by one frame (timestep seconds, substeps substeps).
Public Attributes
scalar timestep = 1.0 / 60.0
Frame duration in seconds.
int substeps = 20
Substeps per frame; higher = more stable, more expensive.
BodyCollection bodies
All rigid bodies.
ConstraintCollection constraints
Low-level constraint rows (joints, contacts share this pool).
JointCollection joints
High-level joints (each owns several constraint rows).
ContactList contacts
Output of the per-frame contact pipeline.
ColliderCollection colliders
All colliders (shape + material + offset).
rbc::BroadPhaseState broad_phase_state
SAP broad-phase scratch and outputs.
Detailed Description
Owns the simulation state and runs the per-frame step loop.
Plain aggregate of the underlying collections: callers can poke at the data arrays directly when they need to (e.g. world.bodies.position[i]). The create_* helpers wrap the corresponding free-function rbps::create_* so the broad phase / constraint book-keeping is kept consistent.
Examples
test_world.cpp.
Definition at line 87 of file World.hpp.
Member Function Documentation
create_body()
uint32_t rbps::World::create_body (BodyParams params) inline
Create a body.
Returns its stable ID.
Examples
test_world.cpp.
Definition at line 113 of file World.hpp.
References bodies, and rbps::create_body().
Referenced by visr::dispatch_command().
create_collider()
uint32_t rbps::World::create_collider (ColliderParams params) inline
Create a collider attached to an existing body.
The world transform is computed from the owning body so the broad-phase AABB is correct on the first frame.
Definition at line 124 of file World.hpp.
References bodies, rbps::ColliderParams::body_id, broad_phase_state, colliders, and rbps::create_collider().
Referenced by visr::dispatch_command().
solve_positions()
void rbps::World::solve_positions (scalar inv_h, scalar h) inline
Position-level solver for one substep.
Reuses the contact set built once at frame start; lambdas accumulate across substeps. Do NOT clear contacts here.
Definition at line 168 of file World.hpp.
References bodies, rbps::compute_joint_errors(), constraints, contacts, joints, rbps::solve_constraints(), and rbps::solve_contacts_position_level().
Referenced by step().
step()
void rbps::World::step () inline
Advance the simulation by one frame (timestep seconds, substeps substeps).
Runs the broad/narrow phase once per frame (per the XPBD step loop diagram in this file's overview) then iterates the position-level and velocity-level solvers substeps times.
Examples
test_world.cpp.
Definition at line 192 of file World.hpp.
References bodies, broad_phase_state, rbc::broad_phase_update(), rbps::ContactList::clear(), colliders, contacts, rbc::BroadPhaseState::pairs, rbps::ContactList::reserve(), rbps::run_narrow_phase(), solve_positions(), solve_velocities(), substeps, timestep, rbps::update_broad_phase_aabbs(), rbps::update_position_and_orientation(), and rbps::update_velocities().
The documentation for this struct was generated from the following file:
/home/runner/work/rbps/rbps/include/rbps/API/World.hpp