RBPS: m3d::smat3 Struct Reference
m3d::smat3 Struct Reference
math3d — 3D math primitives
Symmetric 3×3 matrix stored as 6 unique scalars.
#include <mat3.hpp>
Public Member Functions
smat3 ()
Zero matrix.
smat3 (scalar xx, scalar yy, scalar zz, scalar xy, scalar xz, scalar yz)
Component-wise constructor (diagonal first, then upper-triangle).
smat3 (const mat3 &m)
Construct from a dense mat3, projecting it onto the symmetric subspace.
vec3 operator* (const vec3 &v) const
Symmetric matrix–vector product.
smat3 operator* (scalar s) const
Component-wise scaling.
scalar determinant () const
3×3 determinant via the symmetric formula.
smat3 inverse () const
Inverse, preserved as a symmetric matrix.
bool is_approx (const smat3 &o, scalar p=EPSILON) const
Tolerance-based equality (per-element).
Public Attributes
scalar zz
Diagonal entries.
scalar yz
Upper-triangle off-diagonal entries.
Friends
std::ostream & operator<< (std::ostream &os, const smat3 &m)
Stream insertion summarising the diagonal and off-diagonal entries.
Detailed Description
Symmetric 3×3 matrix stored as 6 unique scalars.
Used for the inertia tensor (which is always symmetric). Storing only the upper triangle saves memory and lets the operators exploit symmetry for slightly cheaper math.
Layout when expanded to a dense matrix:
| xx  xy  xz |
| xy  yy  yz |
| xz  yz  zz |
Examples
test_body.cpp.
Definition at line 196 of file mat3.hpp.
Constructor & Destructor Documentation
smat3()
m3d::smat3::smat3 (const mat3 & m) inline explicit
Construct from a dense mat3, projecting it onto the symmetric subspace.
Off-diagonal entries are averaged ((m_ij + m_ji) / 2) so a slightly non-symmetric input is silently cleaned up rather than preserving one side and discarding the other.
Definition at line 214 of file mat3.hpp.
Member Function Documentation
inverse()
smat3 m3d::smat3::inverse () const inline
Inverse, preserved as a symmetric matrix.
Returns the zero matrix when the determinant is below EPSILON.
Definition at line 246 of file mat3.hpp.
References m3d::abs(), determinant(), m3d::EPSILON, smat3(), yz, and zz.
is_approx()
bool m3d::smat3::is_approx (const smat3 & o, scalar p = EPSILON) const inline
Tolerance-based equality (per-element).
Parameters
o Matrix to compare against.
p Absolute per-element tolerance (default EPSILON).
Definition at line 273 of file mat3.hpp.
References m3d::abs(), yz, and zz.
The documentation for this struct was generated from the following file:
/home/runner/work/rbps/rbps/include/math3d/mat3.hpp